// Generated by scripts/sync-planner-texts.mjs from the app's i18n (fr.js). Do not edit:
// change the texts in the app, or override them in fr.js next to this file.
export default {
  "common": {
    "add": "Ajouter",
    "apply": "Appliquer",
    "back": "Retour",
    "cancel": "Annuler",
    "change": "Modifier",
    "close": "Fermer",
    "howItWorks": "Comment ça marche",
    "loading": "Chargement …",
    "next": "Suivant",
    "undo": "Annuler"
  },
  "confirm": {
    "startOver": {
      "title": "Recommencer ?",
      "text": "Toutes les saisies sur cet appareil seront effacées.",
      "ok": "Tout effacer"
    }
  },
  "setup": {
    "progress": "Progression",
    "stepOf": "Étape {n} sur {total}",
    "steps": {
      "house": "Immeuble",
      "machines": "Buanderie",
      "times": "Horaires",
      "plan": "Tournus fixe",
      "rules": "Règles",
      "account": "Accès"
    },
    "savedLocally": "Vos saisies restent sur cet appareil jusqu’à ce que vous créiez l’immeuble.",
    "startOver": "Recommencer",
    "block": {
      "houseName": "Donnez un nom à l’immeuble.",
      "flatNames": "Chaque appartement a besoin d’un nom.",
      "machines": "Choisissez au moins une machine ou une pièce.",
      "machineNames": "Tout a besoin d’un nom.",
      "times": "Choisissez au moins un jour.",
      "timeErrors": "Veuillez corriger les horaires marqués.",
      "name": "Indiquez votre nom.",
      "email": "Indiquez une adresse e-mail valable.",
      "password": "Le mot de passe doit avoir au moins 8 caractères."
    },
    "house": {
      "title": "Bienvenue ! Parlez-nous de votre immeuble",
      "lead": "Votre plan de lessive est prêt en six étapes courtes. Vous pourrez tout modifier plus tard.",
      "name": "Nom de l’immeuble",
      "namePh": "par ex. Rue du Lac 12",
      "nameHint": "Affiché en haut du planning et sur l’affiche.",
      "flatsTitle": "Appartements",
      "count": "Combien d’appartements partagent la buanderie ?",
      "names": "Comment s’appellent les appartements ?",
      "quickFill": "Remplir vite :",
      "fillNumbers": "Appartement 1, 2, 3 …",
      "fillFloors2": "Rez gauche, droite …",
      "fillFloors1": "Rez, étage 1 …",
      "colorLabel": "Couleur de {name}",
      "colorHint": "Touchez un point pour changer la couleur de l’appartement dans le planning.",
      "flatN": "Appartement {n}",
      "flatLabel": "Nom de l’appartement {n}",
      "groundFloor": "Rez",
      "floorN": "Étage {n}",
      "sides1": "",
      "sides2": "gauche,droite",
      "sides3": "gauche,milieu,droite",
      "privacyTip": "Conseil : utilisez des désignations comme « Étage 2 gauche » plutôt que des noms de famille. Le planning peut aussi être affiché sur un écran dans la buanderie.",
      "liveHere": "Habitez-vous vous-même dans l’un de ces appartements ?",
      "notLiving": "Non, je gère seulement l’immeuble",
      "liveHereHint": "Vous pourrez alors aussi réserver pour votre appartement."
    },
    "machines": {
      "title": "Qu’y a-t-il dans votre buanderie ?",
      "lead": "Indiquez ce qui se réserve. Inutile d’indiquer ce que personne ne réserve (comme une planche à repasser).",
      "example": {
        "washer": "Laver le linge",
        "dryer": "Sécher le linge en machine",
        "drying_room": "Pièce pour étendre le linge",
        "other": "par ex. local de repassage"
      },
      "howTitle": "Comment réserve-t-on ?",
      "together": "Tout ensemble",
      "togetherHint": "Celui ou celle dont c’est le tour a toute la buanderie avec toutes les machines. Typique pour un jour de lessive fixe.",
      "separate": "Chaque chose séparément",
      "separateHint": "Chaque machine et chaque pièce se réserve séparément. Plusieurs appartements peuvent faire la lessive en même temps.",
      "mixed": "Mixte",
      "mixedHint": "Vous décidez de ce qui va ensemble. Par exemple lave-linge et sèche-linge ensemble, le séchoir séparément.",
      "help1": "Exemple « tout ensemble » : l’appartement A a le lundi le lave-linge, le sèche-linge et le séchoir.",
      "help2": "Exemple « séparément » : l’appartement A lave le lundi matin pendant que l’appartement B étend son linge au séchoir.",
      "namesTitle": "Noms dans le planning",
      "togetherName": "Nom dans le planning",
      "mixedIntro": "Ce qui a le même numéro se réserve ensemble.",
      "groupN": "Groupe {n}",
      "groupOf": "Groupe de {name}",
      "groupNameLabel": "Nom du groupe {n}",
      "roomN": "Buanderie {n}",
      "previewTitle": "Ce qui se réserve",
      "previewCount": "{n} entrée dans le planning|{n} entrées dans le planning"
    },
    "times": {
      "title": "Quand peut-on faire la lessive ?",
      "lead": "Choisissez les jours et divisez chaque jour en créneaux. Un créneau est le temps qu’un appartement réserve d’un coup.",
      "help1": "Suivez le règlement de maison. Souvent, la lessive est permise de 7 h à 22 h et pas le dimanche.",
      "help2": "Des créneaux plus courts permettent à plus d’appartements de passer chaque jour. Une journée entière est pratique s’il y a peu d’appartements.",
      "helpUnits": "Ces horaires valent pour tout ce qui se réserve. Plus tard, sous « Gérer », vous pourrez fixer d’autres horaires par machine."
    },
    "plan": {
      "title": "Qui fait la lessive quand ?",
      "lead": "Dans le tournus fixe, chaque appartement a ses propres créneaux – comme un événement qui se répète dans un agenda. Ce qui reste libre, chaque appartement peut le réserver.",
      "help1": "Choisissez un créneau pour le donner à un appartement : chaque semaine, toutes les 2 semaines ou une fois par mois.",
      "help2": "Plusieurs appartements peuvent partager un créneau, par exemple en alternance une semaine sur deux.",
      "help3": "À droite, vous voyez combien de temps chaque appartement reçoit par mois. Choisissez un appartement pour voir ses créneaux et en ajouter un.",
      "suggested": "Nous avons fait une proposition équitable. Adaptez-la ou laissez tout libre à la réservation."
    }
  },
  "slots": {
    "days": "Quels jours ?",
    "closed": "fermé",
    "openingHours": "De quelle heure à quelle heure ?",
    "from": "de",
    "to": "à",
    "openingHint": "La première lessive commence au plus tôt et la dernière se termine au plus tard à ces heures.",
    "divisionTitle": "Comment la journée est-elle divisée ?",
    "division": {
      "day": "Journée entière",
      "two": "2 créneaux",
      "three": "3 créneaux",
      "twoHours": "Toutes les 2 heures",
      "custom": "Horaires libres"
    },
    "divisionHint": {
      "day": "Un appartement par jour.",
      "two": "Matin et après-midi.",
      "three": "Matin, midi, soir.",
      "twoHours": "Beaucoup de créneaux courts.",
      "custom": "Vous fixez chaque créneau vous-même."
    },
    "customTitle": "Créneaux",
    "perDayTitle": "Choisir un jour",
    "perDaySwitch": "Autres horaires certains jours (par ex. plus courts le samedi)",
    "differs": "Diffère du premier jour",
    "copyToAll": "Reprendre les horaires du {day} pour tous les jours",
    "add": "Ajouter un créneau",
    "remove": "Supprimer le créneau",
    "previewTitle": "Aperçu : une semaine",
    "summary": "{n} créneaux par semaine · {hours} heures",
    "fixErrors": "Veuillez corriger les horaires.",
    "errorOrder": "Un créneau doit finir après son début.",
    "errorShort": "Un créneau dure au moins 30 minutes.",
    "errorOverlap": "Deux créneaux se chevauchent."
  },
  "plan": {
    "free": "Libre",
    "mixed": "Diffère selon la machine",
    "scope": "Pour quelle machine ?",
    "scopeAll": "Toutes pareilles",
    "view": "Vue",
    "viewWeek": "Semaine type",
    "viewCalendar": "Calendrier",
    "calendarTitle": "Les prochaines semaines",
    "clickHint": "Choisissez un créneau pour le modifier. Pour le déplacer, faites-le glisser sur un autre (sur le téléphone : appuyer, maintenir et glisser).",
    "mode": "Outil",
    "modeEdit": "Modifier",
    "modePaint": "Peindre",
    "drop": {
      "move": "Relâcher pour déplacer",
      "swap": "Relâcher pour échanger",
      "moved": "Déplacé",
      "swapped": "Échangé"
    },
    "paint": {
      "brush": "Pinceau :",
      "free": "Libre",
      "hint": "Touchez des créneaux ou glissez dessus : ils vont à « {name} ». « Annuler » retire tout un trait.",
      "everyOtherThis": "Toutes les 2 semaines, dès cette semaine",
      "everyOtherNext": "Toutes les 2 semaines, dès la semaine prochaine"
    },
    "autoBtn": "Répartir automatiquement",
    "clearBtn": "Tout libérer",
    "noSlots": "Il n’y a pas encore de créneaux. Définissez-les sous « Machines et horaires ».",
    "adminLead": "Quel appartement fait régulièrement la lessive, et quand.",
    "adminHelp": "Les modifications s’appliquent tout de suite à toutes les semaines à venir. Les réservations des résident·es restent telles quelles.",
    "stats": {
      "title": "Temps par appartement",
      "perMonth": "en moyenne par mois",
      "days": "{n} jours",
      "hours": "{n} h",
      "noTime": "pas de créneau fixe",
      "highlight": "Afficher et modifier les créneaux de cet appartement",
      "free": "Libre pour tous : environ {n} créneaux par mois",
      "missing": "{names} n’a pas encore de créneau fixe.|{names} n’ont pas encore de créneau fixe.",
      "uneven": "Le temps n’est pas réparti équitablement. C’est bien si c’est convenu ainsi."
    },
    "party": {
      "none": "Cet appartement n’a pas encore de créneau fixe.",
      "remove": "Supprimer ce créneau",
      "addTitle": "Ajouter un créneau",
      "day": "Jour",
      "time": "Créneau",
      "add": "Ajouter",
      "wholeDay": "Journée entière",
      "added": "Ajouté",
      "already": "Cet appartement a déjà ce créneau ainsi.",
      "taken": "{name} a déjà ce créneau avec la même répétition. Choisissez une autre répétition ou modifiez-le dans la semaine."
    },
    "dialog": {
      "intro": "À qui est ce créneau, et à quelle fréquence ?",
      "mixed": "Les machines ont ici des entrées différentes. Ce que vous définissez maintenant vaut pour toutes. Pour modifier une seule machine, choisissez-la plus haut sous « Pour quelle machine ? ».",
      "empty": "Ce créneau est libre. À qui doit-il appartenir ?",
      "who": "Appartement",
      "repeat": "Répétition",
      "startingOn": "La première fois le",
      "onThe": "Chaque mois le",
      "nthWeekday": "{nth} {day}",
      "remove": "Supprimer",
      "addParty": "Un autre appartement",
      "addPartyPh": "Choisir un appartement …",
      "addHint": "Plusieurs appartements alternent, par ex. une semaine sur deux.",
      "duplicate": "Deux entrées ont la même règle. Veuillez en modifier une.",
      "upcoming": "Prochaines dates",
      "instead": "a la priorité sur {names}",
      "clear": "Libérer ce créneau"
    },
    "auto": {
      "title": "Répartir automatiquement",
      "intro": "Les créneaux sont distribués à tour de rôle, dès cette semaine. Ensuite, vous pouvez tout ajuster individuellement.",
      "days": "Journées entières",
      "daysHint": "Chaque appartement reçoit des journées entières.",
      "slots": "Créneaux isolés",
      "slotsHint": "Chaque appartement reçoit des créneaux isolés.",
      "once": "Une fois par tour",
      "onceHint": "Le reste reste libre pour les réservations supplémentaires.",
      "all": "Aussi souvent que possible",
      "allHint": "Tout est réparti équitablement.",
      "unit": {
        "days": "jour|jours",
        "slots": "créneau|créneaux"
      },
      "eachWeekly": "Chaque appartement reçoit {n} {unit} par semaine.",
      "eachEveryN": "Chaque appartement reçoit {n} {unit} toutes les {weeks} semaines.",
      "freeWeekly": "{n} {unit} par semaine reste libre pour tous.|{n} {unit} par semaine restent libres pour tous.",
      "freeCycle": "Sur {weeks} semaines, {n} {unit} reste libre pour tous.|Sur {weeks} semaines, {n} {unit} restent libres pour tous.",
      "noneFree": "Rien ne reste libre.",
      "tooMany": "Il y a trop peu de créneaux pour que chaque appartement ait son tour. Ajoutez des jours ou des créneaux.",
      "replaces": "Ceci remplace le tournus actuel. Vous pouvez revenir en arrière avec « Annuler ».",
      "apply": "Répartir"
    }
  },
  "rule": {
    "freq": {
      "weekly": "Chaque semaine",
      "everyN": "Toutes les {n} semaines",
      "monthly": "Une fois par mois"
    },
    "nth": {
      "1": "premier",
      "2": "deuxième",
      "3": "troisième",
      "4": "quatrième",
      "last": "dernier"
    },
    "short": {
      "everyN": "ttes les {n} sem.",
      "monthly": {
        "1": "1er du mois",
        "2": "2e du mois",
        "3": "3e du mois",
        "4": "4e du mois",
        "last": "dernier du mois"
      }
    },
    "long": {
      "weekly": "Chaque {day}",
      "everyOther": "Un {day} sur deux",
      "everyN": "Toutes les {n} semaines le {day}",
      "monthly": {
        "1": "Le premier {day} du mois",
        "2": "Le deuxième {day} du mois",
        "3": "Le troisième {day} du mois",
        "4": "Le quatrième {day} du mois",
        "last": "Le dernier {day} du mois"
      }
    }
  },
  "kind": {
    "washer": "Lave-linge",
    "dryer": "Sèche-linge",
    "drying_room": "Séchoir",
    "other": "Autre",
    "laundry_room": "Buanderie",
    "plural": {
      "washer": "Lave-linge",
      "dryer": "Sèche-linge",
      "drying_room": "Séchoirs",
      "other": "Autres"
    }
  },
  "print": {
    "lead": "Deux semaines par page A4, à afficher dans la buanderie. Si vous modifiez quelque chose, imprimez simplement à nouveau.",
    "from": "Dès la semaine",
    "pages": "Étendue",
    "pagesOpt": "{n} page · {weeks} semaines|{n} pages · {weeks} semaines",
    "orientation": "Orientation",
    "portrait": "Portrait",
    "landscape": "Paysage",
    "machines": "Machines et pièces",
    "print": "Imprimer",
    "pdfHint": "Dans la fenêtre d’impression, vous pouvez aussi choisir « Enregistrer au format PDF ».",
    "week": "Sem. {n}",
    "time": "Heure",
    "free": "libre",
    "footer": "Créé avec Waschplaner · waschplaner.com",
    "printed": "État au {date}",
    "welcomeTitle": "Votre planning est prêt !",
    "welcomeText": "Imprimez-le et affichez-le dans la buanderie. Si vous modifiez quelque chose plus tard, imprimez simplement à nouveau.",
    "none": "Choisissez au moins une machine ou une pièce."
  },
  "rules": {
    "weeks": "{n} semaine|{n} semaines",
    "days": "{n} jour|{n} jours",
    "threeMonths": "3 mois",
    "unit": {
      "days": "jour|jours",
      "slots": "créneau|créneaux"
    },
    "sum": {
      "quota": "Chaque appartement peut réserver {n} {unit} en plus par semaine.",
      "unlimited": "Chaque appartement peut réserver en plus autant de créneaux libres qu’il veut.",
      "none": "Les réservations supplémentaires ne sont pas possibles.",
      "horizon": "On peut réserver jusqu’à {time} à l’avance.",
      "override": {
        "unused_after_grace": "Si un créneau n’est pas utilisé {n} minutes après le début, d’autres peuvent le reprendre.",
        "anytime": "D’autres peuvent reprendre des créneaux à tout moment.",
        "never": "Personne ne peut reprendre le créneau de quelqu’un d’autre."
      }
    }
  }
}
