// Generated by scripts/sync-planner-texts.mjs from the app's i18n (en.js). Do not edit:
// change the texts in the app, or override them in en.js next to this file.
export default {
  "common": {
    "add": "Add",
    "apply": "Apply",
    "back": "Back",
    "cancel": "Cancel",
    "change": "Change",
    "close": "Close",
    "howItWorks": "How it works",
    "loading": "Loading …",
    "next": "Next",
    "undo": "Undo"
  },
  "confirm": {
    "startOver": {
      "title": "Start over?",
      "text": "All entries on this device will be deleted.",
      "ok": "Delete everything"
    }
  },
  "setup": {
    "progress": "Progress",
    "stepOf": "Step {n} of {total}",
    "steps": {
      "house": "House",
      "machines": "Laundry room",
      "times": "Times",
      "plan": "Schedule",
      "rules": "Rules",
      "account": "Login"
    },
    "savedLocally": "Your entries stay on this device until you create the house.",
    "startOver": "Start over",
    "block": {
      "houseName": "Give the house a name.",
      "flatNames": "Every flat needs a name.",
      "machines": "Choose at least one machine or room.",
      "machineNames": "Everything needs a name.",
      "times": "Choose at least one day.",
      "timeErrors": "Please fix the highlighted times.",
      "name": "Enter your name.",
      "email": "Enter a valid e-mail address.",
      "password": "The password needs at least 8 characters."
    },
    "house": {
      "title": "Welcome! Tell us about your house",
      "lead": "Your laundry plan is ready in six short steps. You can change everything later.",
      "name": "Name of the house",
      "namePh": "e.g. 12 Main Street",
      "nameHint": "Shown at the top of the schedule and on the poster.",
      "flatsTitle": "Flats",
      "count": "How many flats share the laundry room?",
      "names": "What are the flats called?",
      "quickFill": "Quick fill:",
      "fillNumbers": "Flat 1, 2, 3 …",
      "fillFloors2": "Ground floor left, right …",
      "fillFloors1": "Ground floor, 1st floor …",
      "colorLabel": "Colour of {name}",
      "colorHint": "Tap a dot to change the flat’s colour in the schedule.",
      "flatN": "Flat {n}",
      "flatLabel": "Name of flat {n}",
      "groundFloor": "Ground floor",
      "floorN": "Floor {n}",
      "sides1": "",
      "sides2": "left,right",
      "sides3": "left,middle,right",
      "privacyTip": "Tip: use labels like “2nd floor left” instead of family names. The schedule may also be shown on a screen in the laundry room.",
      "liveHere": "Do you live in one of these flats yourself?",
      "notLiving": "No, I only manage the house",
      "liveHereHint": "Then you can also book for your own flat."
    },
    "machines": {
      "title": "What is in your laundry room?",
      "lead": "List what can be booked. You do not need to list things nobody books (like an ironing board).",
      "example": {
        "washer": "Wash laundry",
        "dryer": "Dry laundry by machine",
        "drying_room": "Room to hang laundry",
        "other": "e.g. ironing room"
      },
      "howTitle": "How do people book?",
      "together": "All together",
      "togetherHint": "Whoever’s turn it is gets the whole laundry room with all machines. Typical for a fixed laundry day.",
      "separate": "Each one separately",
      "separateHint": "Every machine and room is booked on its own. Several flats can do laundry at the same time.",
      "mixed": "Mixed",
      "mixedHint": "You decide what belongs together. For example washer and dryer together, the drying room separately.",
      "help1": "Example “all together”: flat A has the washing machine, the dryer and the drying room on Monday.",
      "help2": "Example “separately”: flat A washes on Monday morning while flat B hangs up laundry in the drying room.",
      "namesTitle": "Names in the schedule",
      "togetherName": "Name in the schedule",
      "mixedIntro": "Things with the same number are booked together.",
      "groupN": "Group {n}",
      "groupOf": "Group of {name}",
      "groupNameLabel": "Name of group {n}",
      "roomN": "Laundry room {n}",
      "previewTitle": "What can be booked",
      "previewCount": "{n} entry in the schedule|{n} entries in the schedule"
    },
    "times": {
      "title": "When can people do laundry?",
      "lead": "Choose the days and split each day into time slots. A time slot is the time one flat books in one go.",
      "help1": "Follow your house rules. Often laundry is allowed from 7am to 10pm and not on Sundays.",
      "help2": "Shorter time slots mean more flats get a turn each day. A whole day is convenient if there are only a few flats.",
      "helpUnits": "These times apply to everything that can be booked. Later, under “Manage”, you can set different times per machine."
    },
    "plan": {
      "title": "Who does laundry when?",
      "lead": "In the regular schedule every flat has its own time slots – like a repeating event in a calendar. Anything left free can be booked by any flat.",
      "help1": "Select a time slot to give it to a flat: every week, every 2 weeks or once a month.",
      "help2": "Several flats can share a time slot, for example taking turns every other week.",
      "help3": "On the right you see how much time each flat gets per month. Select a flat to see its times and add another one.",
      "suggested": "We made a fair suggestion. Adjust it, or leave everything free to book."
    }
  },
  "slots": {
    "days": "On which days?",
    "closed": "closed",
    "openingHours": "From when until when?",
    "from": "from",
    "to": "until",
    "openingHint": "The first wash starts at the earliest and the last one ends at the latest at these times.",
    "divisionTitle": "How is the day split?",
    "division": {
      "day": "Whole day",
      "two": "2 time slots",
      "three": "3 time slots",
      "twoHours": "Every 2 hours",
      "custom": "Own times"
    },
    "divisionHint": {
      "day": "One flat per day.",
      "two": "Morning and afternoon.",
      "three": "Morning, midday, evening.",
      "twoHours": "Many short time slots.",
      "custom": "You set each time slot yourself."
    },
    "customTitle": "Time slots",
    "perDayTitle": "Choose a day",
    "perDaySwitch": "Different times on some days (e.g. shorter on Saturday)",
    "differs": "Differs from the first day",
    "copyToAll": "Use the times of {day} for all days",
    "add": "Add time slot",
    "remove": "Remove time slot",
    "previewTitle": "Preview: one week",
    "summary": "{n} time slots per week · {hours} hours",
    "fixErrors": "Please fix the times.",
    "errorOrder": "A time slot must end after it starts.",
    "errorShort": "A time slot lasts at least 30 minutes.",
    "errorOverlap": "Two time slots overlap."
  },
  "plan": {
    "free": "Free",
    "mixed": "Differs per machine",
    "scope": "For which machine?",
    "scopeAll": "All the same",
    "view": "View",
    "viewWeek": "Normal week",
    "viewCalendar": "Calendar",
    "calendarTitle": "The next weeks",
    "clickHint": "Select a time slot to change it. To move it, drag it onto another one (on a phone: press, hold and drag).",
    "mode": "Tool",
    "modeEdit": "Edit",
    "modePaint": "Paint",
    "drop": {
      "move": "Release to move",
      "swap": "Release to swap",
      "moved": "Moved",
      "swapped": "Swapped"
    },
    "paint": {
      "brush": "Brush:",
      "free": "Free",
      "hint": "Tap time slots or swipe over them: they go to “{name}”. “Undo” takes back a whole stroke.",
      "everyOtherThis": "Every 2 weeks, from this week",
      "everyOtherNext": "Every 2 weeks, from next week"
    },
    "autoBtn": "Distribute automatically",
    "clearBtn": "Free everything",
    "noSlots": "There are no time slots yet. Set them under “Machines & times”.",
    "adminLead": "Which flat may do laundry when, on a regular basis.",
    "adminHelp": "Changes apply right away to all coming weeks. Individual bookings by residents stay as they are.",
    "stats": {
      "title": "Time per flat",
      "perMonth": "average per month",
      "days": "{n} days",
      "hours": "{n} h",
      "noTime": "no regular time",
      "highlight": "Show and edit this flat’s times",
      "free": "Free for everyone: about {n} time slots per month",
      "missing": "{names} has no regular time yet.|{names} have no regular time yet.",
      "uneven": "Time is not shared equally. That is fine if it was agreed."
    },
    "party": {
      "none": "This flat has no regular time yet.",
      "remove": "Remove this time",
      "addTitle": "Add a time",
      "day": "Day",
      "time": "Time slot",
      "add": "Add",
      "wholeDay": "Whole day",
      "added": "Added",
      "already": "This flat already has this time slot like this.",
      "taken": "{name} already has this time slot with the same repeat. Choose another repeat or change it in the week."
    },
    "dialog": {
      "intro": "Who has this time slot, and how often?",
      "mixed": "The machines have different entries here. What you set now applies to all of them. To edit one machine, choose it above under “For which machine?”.",
      "empty": "This time slot is free. Who should it belong to?",
      "who": "Flat",
      "repeat": "Repeat",
      "startingOn": "First on",
      "onThe": "Each month on the",
      "nthWeekday": "{nth} {day}",
      "remove": "Remove",
      "addParty": "Another flat",
      "addPartyPh": "Choose a flat …",
      "addHint": "Several flats take turns, e.g. every other week.",
      "duplicate": "Two entries have the same rule. Please change one of them.",
      "upcoming": "Next dates",
      "instead": "takes priority over {names}",
      "clear": "Free this time slot"
    },
    "auto": {
      "title": "Distribute automatically",
      "intro": "Time slots are handed out in turn, starting this week. Afterwards you can adjust everything individually.",
      "days": "Whole days",
      "daysHint": "Each flat gets whole days.",
      "slots": "Single time slots",
      "slotsHint": "Each flat gets single time slots.",
      "once": "Once per round",
      "onceHint": "The rest stays free for extra bookings.",
      "all": "As often as possible",
      "allHint": "Everything is shared out evenly.",
      "unit": {
        "days": "day|days",
        "slots": "time slot|time slots"
      },
      "eachWeekly": "Each flat gets {n} {unit} per week.",
      "eachEveryN": "Each flat gets {n} {unit} every {weeks} weeks.",
      "freeWeekly": "{n} {unit} per week stays free for everyone.|{n} {unit} per week stay free for everyone.",
      "freeCycle": "Over {weeks} weeks, {n} {unit} stays free for everyone.|Over {weeks} weeks, {n} {unit} stay free for everyone.",
      "noneFree": "Nothing stays free.",
      "tooMany": "There are too few time slots to give every flat a turn. Add more days or time slots.",
      "replaces": "This replaces the current schedule. You can go back with “Undo”.",
      "apply": "Distribute"
    }
  },
  "rule": {
    "freq": {
      "weekly": "Every week",
      "everyN": "Every {n} weeks",
      "monthly": "Once a month"
    },
    "nth": {
      "1": "first",
      "2": "second",
      "3": "third",
      "4": "fourth",
      "last": "last"
    },
    "short": {
      "everyN": "every {n} wks",
      "monthly": {
        "1": "1st of month",
        "2": "2nd of month",
        "3": "3rd of month",
        "4": "4th of month",
        "last": "last of month"
      }
    },
    "long": {
      "weekly": "Every {day}",
      "everyOther": "Every other {day}",
      "everyN": "Every {n} weeks on {day}",
      "monthly": {
        "1": "The first {day} of the month",
        "2": "The second {day} of the month",
        "3": "The third {day} of the month",
        "4": "The fourth {day} of the month",
        "last": "The last {day} of the month"
      }
    }
  },
  "kind": {
    "washer": "Washing machine",
    "dryer": "Tumble dryer",
    "drying_room": "Drying room",
    "other": "Other",
    "laundry_room": "Laundry room",
    "plural": {
      "washer": "Washing machines",
      "dryer": "Tumble dryers",
      "drying_room": "Drying rooms",
      "other": "Other"
    }
  },
  "print": {
    "lead": "Two weeks per A4 page, to hang up in the laundry room. If you change something, simply print again.",
    "from": "From week",
    "pages": "Length",
    "pagesOpt": "{n} page · {weeks} weeks|{n} pages · {weeks} weeks",
    "orientation": "Orientation",
    "portrait": "Portrait",
    "landscape": "Landscape",
    "machines": "Machines and rooms",
    "print": "Print",
    "pdfHint": "In the print dialog you can also choose “Save as PDF”.",
    "week": "Week {n}",
    "time": "Time",
    "free": "free",
    "footer": "Made with Waschplaner · waschplaner.com",
    "printed": "As of {date}",
    "welcomeTitle": "Your schedule is ready!",
    "welcomeText": "Print it and hang it up in the laundry room. If you change something later, simply print again.",
    "none": "Choose at least one machine or room."
  },
  "rules": {
    "weeks": "{n} week|{n} weeks",
    "days": "{n} day|{n} days",
    "threeMonths": "3 months",
    "unit": {
      "days": "day|days",
      "slots": "time slot|time slots"
    },
    "sum": {
      "quota": "Each flat may book {n} extra {unit} per week.",
      "unlimited": "Each flat may book any number of free time slots extra.",
      "none": "Extra bookings are not possible.",
      "horizon": "Bookings can be made up to {time} ahead.",
      "override": {
        "unused_after_grace": "If a time slot is not used {n} minutes after it starts, others may take it over.",
        "anytime": "Others may take over time slots at any time.",
        "never": "Nobody can take over someone else’s time slot."
      }
    }
  }
}
