// Generated by scripts/sync-planner-texts.mjs from the app's i18n (it.js). Do not edit:
// change the texts in the app, or override them in it.js next to this file.
export default {
  "common": {
    "add": "Aggiungi",
    "apply": "Applica",
    "back": "Indietro",
    "cancel": "Annulla",
    "change": "Modifica",
    "close": "Chiudi",
    "howItWorks": "Come funziona",
    "loading": "Caricamento …",
    "next": "Avanti",
    "undo": "Annulla"
  },
  "confirm": {
    "startOver": {
      "title": "Ricominciare?",
      "text": "Tutti i dati inseriti su questo dispositivo verranno cancellati.",
      "ok": "Cancella tutto"
    }
  },
  "setup": {
    "progress": "Avanzamento",
    "stepOf": "Passo {n} di {total}",
    "steps": {
      "house": "Palazzo",
      "machines": "Lavanderia",
      "times": "Orari",
      "plan": "Turni fissi",
      "rules": "Regole",
      "account": "Accesso"
    },
    "savedLocally": "I tuoi dati restano su questo dispositivo finché crei il palazzo.",
    "startOver": "Ricomincia",
    "block": {
      "houseName": "Dai un nome al palazzo.",
      "flatNames": "Ogni appartamento ha bisogno di un nome.",
      "machines": "Scegli almeno una macchina o un locale.",
      "machineNames": "Tutto ha bisogno di un nome.",
      "times": "Scegli almeno un giorno.",
      "timeErrors": "Correggi gli orari evidenziati.",
      "name": "Inserisci il tuo nome.",
      "email": "Inserisci un indirizzo e-mail valido.",
      "password": "La password deve avere almeno 8 caratteri."
    },
    "house": {
      "title": "Benvenuto! Raccontaci del tuo palazzo",
      "lead": "In sei brevi passi il vostro piano del bucato è pronto. Potrai cambiare tutto più tardi.",
      "name": "Nome del palazzo",
      "namePh": "ad es. Via Lago 12",
      "nameHint": "Appare in alto nel piano e sull’avviso.",
      "flatsTitle": "Appartamenti",
      "count": "Quanti appartamenti condividono la lavanderia?",
      "names": "Come si chiamano gli appartamenti?",
      "quickFill": "Compila in fretta:",
      "fillNumbers": "Appartamento 1, 2, 3 …",
      "fillFloors2": "Pianterreno sinistra, destra …",
      "fillFloors1": "Pianterreno, 1° piano …",
      "colorLabel": "Colore di {name}",
      "colorHint": "Tocca un punto per cambiare il colore dell’appartamento nel piano.",
      "flatN": "Appartamento {n}",
      "flatLabel": "Nome dell’appartamento {n}",
      "groundFloor": "Pianterreno",
      "floorN": "{n}° piano",
      "sides1": "",
      "sides2": "sinistra,destra",
      "sides3": "sinistra,centro,destra",
      "privacyTip": "Consiglio: usa nomi come «2° piano sinistra» invece dei cognomi. Il piano può anche essere mostrato su uno schermo in lavanderia.",
      "liveHere": "Abiti anche tu in uno di questi appartamenti?",
      "notLiving": "No, gestisco solo il palazzo",
      "liveHereHint": "Così puoi prenotare anche per il tuo appartamento."
    },
    "machines": {
      "title": "Cosa c’è nella tua lavanderia?",
      "lead": "Indica ciò che si prenota. Non serve indicare ciò che nessuno prenota (come un asse da stiro).",
      "example": {
        "washer": "Lavare il bucato",
        "dryer": "Asciugare il bucato a macchina",
        "drying_room": "Locale per stendere il bucato",
        "other": "ad es. locale da stiro"
      },
      "howTitle": "Come si prenota?",
      "together": "Tutto insieme",
      "togetherHint": "Chi è di turno ha tutta la lavanderia con tutte le macchine. Tipico per un giorno fisso del bucato.",
      "separate": "Ognuno per sé",
      "separateHint": "Ogni macchina e ogni locale si prenota da solo. Più appartamenti possono fare il bucato allo stesso tempo.",
      "mixed": "Misto",
      "mixedHint": "Decidi tu cosa va insieme. Ad esempio lavatrice e asciugatrice insieme, il locale asciugatura a parte.",
      "help1": "Esempio «tutto insieme»: l’appartamento A ha il lunedì la lavatrice, l’asciugatrice e il locale asciugatura.",
      "help2": "Esempio «ognuno per sé»: l’appartamento A lava il lunedì mattina mentre l’appartamento B stende il bucato nel locale asciugatura.",
      "namesTitle": "Nomi nel piano",
      "togetherName": "Nome nel piano",
      "mixedIntro": "Ciò che ha lo stesso numero si prenota insieme.",
      "groupN": "Gruppo {n}",
      "groupOf": "Gruppo di {name}",
      "groupNameLabel": "Nome del gruppo {n}",
      "roomN": "Lavanderia {n}",
      "previewTitle": "Cosa si prenota",
      "previewCount": "{n} voce nel piano|{n} voci nel piano"
    },
    "times": {
      "title": "Quando si può fare il bucato?",
      "lead": "Scegli i giorni e dividi ogni giorno in fasce orarie. Una fascia oraria è il tempo che un appartamento prenota in una volta.",
      "help1": "Segui il regolamento della casa. Spesso il bucato è permesso dalle 7 alle 22 e non la domenica.",
      "help2": "Fasce orarie più brevi permettono a più appartamenti di avere il turno ogni giorno. Un giorno intero è comodo se gli appartamenti sono pochi.",
      "helpUnits": "Questi orari valgono per tutto ciò che si prenota. Più tardi, in «Gestisci», puoi fissare orari diversi per ogni macchina."
    },
    "plan": {
      "title": "Chi fa il bucato quando?",
      "lead": "Nei turni fissi ogni appartamento ha le sue fasce orarie – come un evento che si ripete in un calendario. Quello che resta libero, ogni appartamento può prenotarlo.",
      "help1": "Scegli una fascia oraria per darla a un appartamento: ogni settimana, ogni 2 settimane o una volta al mese.",
      "help2": "Più appartamenti possono dividersi una fascia oraria, ad esempio a settimane alterne.",
      "help3": "A destra vedi quanto tempo riceve ogni appartamento al mese. Scegli un appartamento per vederne gli orari e aggiungerne uno.",
      "suggested": "Abbiamo fatto una proposta equa. Adattala, o lascia tutto libero da prenotare."
    }
  },
  "slots": {
    "days": "In quali giorni?",
    "closed": "chiuso",
    "openingHours": "Da che ora a che ora?",
    "from": "dalle",
    "to": "alle",
    "openingHint": "Il primo bucato inizia al più presto e l’ultimo finisce al più tardi a questi orari.",
    "divisionTitle": "Come è diviso il giorno?",
    "division": {
      "day": "Giorno intero",
      "two": "2 fasce orarie",
      "three": "3 fasce orarie",
      "twoHours": "Ogni 2 ore",
      "custom": "Orari propri"
    },
    "divisionHint": {
      "day": "Un appartamento al giorno.",
      "two": "Mattina e pomeriggio.",
      "three": "Mattina, mezzogiorno, sera.",
      "twoHours": "Tante fasce orarie brevi.",
      "custom": "Stabilisci tu ogni fascia oraria."
    },
    "customTitle": "Fasce orarie",
    "perDayTitle": "Scegli un giorno",
    "perDaySwitch": "Orari diversi in alcuni giorni (ad es. più brevi il sabato)",
    "differs": "Diverso dal primo giorno",
    "copyToAll": "Usa gli orari di {day} per tutti i giorni",
    "add": "Aggiungi fascia oraria",
    "remove": "Rimuovi fascia oraria",
    "previewTitle": "Anteprima: una settimana",
    "summary": "{n} fasce orarie alla settimana · {hours} ore",
    "fixErrors": "Correggi gli orari.",
    "errorOrder": "Una fascia oraria deve finire dopo l’inizio.",
    "errorShort": "Una fascia oraria dura almeno 30 minuti.",
    "errorOverlap": "Due fasce orarie si sovrappongono."
  },
  "plan": {
    "free": "Libero",
    "mixed": "Diverso per macchina",
    "scope": "Per quale macchina?",
    "scopeAll": "Tutte uguali",
    "view": "Vista",
    "viewWeek": "Settimana tipo",
    "viewCalendar": "Calendario",
    "calendarTitle": "Le prossime settimane",
    "clickHint": "Scegli una fascia oraria per modificarla. Per spostarla, trascinala su un’altra (sul telefono: premi, tieni premuto e trascina).",
    "mode": "Strumento",
    "modeEdit": "Modifica",
    "modePaint": "Dipingi",
    "drop": {
      "move": "Rilascia per spostare",
      "swap": "Rilascia per scambiare",
      "moved": "Spostata",
      "swapped": "Scambiate"
    },
    "paint": {
      "brush": "Pennello:",
      "free": "Libero",
      "hint": "Tocca le fasce orarie o passaci sopra: vanno a «{name}». «Annulla» toglie un tratto intero.",
      "everyOtherThis": "Ogni 2 settimane, da questa settimana",
      "everyOtherNext": "Ogni 2 settimane, dalla prossima settimana"
    },
    "autoBtn": "Distribuisci automaticamente",
    "clearBtn": "Libera tutto",
    "noSlots": "Non ci sono ancora fasce orarie. Impostale in «Macchine e orari».",
    "adminLead": "Quale appartamento fa regolarmente il bucato, e quando.",
    "adminHelp": "Le modifiche valgono subito per tutte le settimane future. Le prenotazioni dei residenti restano come sono.",
    "stats": {
      "title": "Tempo per appartamento",
      "perMonth": "in media al mese",
      "days": "{n} giorni",
      "hours": "{n} h",
      "noTime": "nessun turno fisso",
      "highlight": "Mostra e modifica gli orari di questo appartamento",
      "free": "Libero per tutti: circa {n} fasce orarie al mese",
      "missing": "{names} non ha ancora un turno fisso.|{names} non hanno ancora un turno fisso.",
      "uneven": "Il tempo non è diviso in parti uguali. Va bene se è stato concordato."
    },
    "party": {
      "none": "Questo appartamento non ha ancora un turno fisso.",
      "remove": "Rimuovi questo orario",
      "addTitle": "Aggiungi un orario",
      "day": "Giorno",
      "time": "Fascia oraria",
      "add": "Aggiungi",
      "wholeDay": "Giorno intero",
      "added": "Aggiunto",
      "already": "Questo appartamento ha già questa fascia oraria così.",
      "taken": "{name} ha già questa fascia oraria con la stessa ripetizione. Scegli un’altra ripetizione o cambiala nella settimana."
    },
    "dialog": {
      "intro": "Di chi è questa fascia oraria, e quanto spesso?",
      "mixed": "Qui le macchine hanno voci diverse. Ciò che imposti ora vale per tutte. Per modificarne una sola, sceglila sopra in «Per quale macchina?».",
      "empty": "Questa fascia oraria è libera. A chi deve appartenere?",
      "who": "Appartamento",
      "repeat": "Ripetizione",
      "startingOn": "La prima volta il",
      "onThe": "Ogni mese:",
      "nthWeekday": "{day}, {nth} settimana",
      "remove": "Rimuovi",
      "addParty": "Un altro appartamento",
      "addPartyPh": "Scegli un appartamento …",
      "addHint": "Più appartamenti si alternano, ad es. a settimane alterne.",
      "duplicate": "Due voci hanno la stessa regola. Cambiane una.",
      "upcoming": "Prossime date",
      "instead": "ha la precedenza su {names}",
      "clear": "Libera questa fascia oraria"
    },
    "auto": {
      "title": "Distribuisci automaticamente",
      "intro": "Le fasce orarie vengono assegnate a turno, a partire da questa settimana. Dopo puoi adattare tutto singolarmente.",
      "days": "Giorni interi",
      "daysHint": "Ogni appartamento riceve giorni interi.",
      "slots": "Singole fasce orarie",
      "slotsHint": "Ogni appartamento riceve singole fasce orarie.",
      "once": "Una volta per giro",
      "onceHint": "Il resto rimane libero per le prenotazioni in più.",
      "all": "Il più spesso possibile",
      "allHint": "Tutto viene diviso in modo uniforme.",
      "unit": {
        "days": "giorno|giorni",
        "slots": "fascia oraria|fasce orarie"
      },
      "eachWeekly": "Ogni appartamento riceve {n} {unit} alla settimana.",
      "eachEveryN": "Ogni appartamento riceve {n} {unit} ogni {weeks} settimane.",
      "freeWeekly": "{n} {unit} alla settimana rimane a disposizione di tutti.|{n} {unit} alla settimana rimangono a disposizione di tutti.",
      "freeCycle": "In {weeks} settimane {n} {unit} rimane a disposizione di tutti.|In {weeks} settimane {n} {unit} rimangono a disposizione di tutti.",
      "noneFree": "Non resta nulla di libero.",
      "tooMany": "Ci sono troppo poche fasce orarie perché ogni appartamento abbia un turno. Aggiungi giorni o fasce orarie.",
      "replaces": "Questo sostituisce il piano attuale. Puoi tornare indietro con «Annulla».",
      "apply": "Distribuisci"
    }
  },
  "rule": {
    "freq": {
      "weekly": "Ogni settimana",
      "everyN": "Ogni {n} settimane",
      "monthly": "Una volta al mese"
    },
    "nth": {
      "1": "1ª",
      "2": "2ª",
      "3": "3ª",
      "4": "4ª",
      "last": "ultima"
    },
    "short": {
      "everyN": "ogni {n} sett.",
      "monthly": {
        "1": "1ª sett. del mese",
        "2": "2ª sett. del mese",
        "3": "3ª sett. del mese",
        "4": "4ª sett. del mese",
        "last": "ultima sett. del mese"
      }
    },
    "long": {
      "weekly": "Ogni {day}",
      "everyOther": "Ogni 2 settimane, {day}",
      "everyN": "Ogni {n} settimane, {day}",
      "monthly": {
        "1": "{day} della 1ª settimana del mese",
        "2": "{day} della 2ª settimana del mese",
        "3": "{day} della 3ª settimana del mese",
        "4": "{day} della 4ª settimana del mese",
        "last": "{day} dell’ultima settimana del mese"
      }
    }
  },
  "kind": {
    "washer": "Lavatrice",
    "dryer": "Asciugatrice",
    "drying_room": "Locale asciugatura",
    "other": "Altro",
    "laundry_room": "Lavanderia",
    "plural": {
      "washer": "Lavatrici",
      "dryer": "Asciugatrici",
      "drying_room": "Locali asciugatura",
      "other": "Altro"
    }
  },
  "print": {
    "lead": "Due settimane per pagina A4, da appendere in lavanderia. Se cambi qualcosa, stampa semplicemente di nuovo.",
    "from": "Dalla settimana",
    "pages": "Estensione",
    "pagesOpt": "{n} pagina · {weeks} settimane|{n} pagine · {weeks} settimane",
    "orientation": "Orientamento",
    "portrait": "Verticale",
    "landscape": "Orizzontale",
    "machines": "Macchine e locali",
    "print": "Stampa",
    "pdfHint": "Nella finestra di stampa puoi anche scegliere «Salva come PDF».",
    "week": "Sett. {n}",
    "time": "Ora",
    "free": "libero",
    "footer": "Creato con Waschplaner · waschplaner.com",
    "printed": "Stato al {date}",
    "welcomeTitle": "Il vostro piano è pronto!",
    "welcomeText": "Stampalo e appendilo in lavanderia. Se più tardi cambi qualcosa, stampa semplicemente di nuovo.",
    "none": "Scegli almeno una macchina o un locale."
  },
  "rules": {
    "weeks": "{n} settimana|{n} settimane",
    "days": "{n} giorno|{n} giorni",
    "threeMonths": "3 mesi",
    "unit": {
      "days": "giorno|giorni",
      "slots": "fascia oraria|fasce orarie"
    },
    "sum": {
      "quota": "Ogni appartamento può prenotare {n} {unit} in più alla settimana.",
      "unlimited": "Ogni appartamento può prenotare in più quante fasce libere vuole.",
      "none": "Le prenotazioni in più non sono possibili.",
      "horizon": "Si può prenotare fino a {time} in anticipo.",
      "override": {
        "unused_after_grace": "Se una fascia oraria non è usata {n} minuti dopo l’inizio, altri possono rilevarla.",
        "anytime": "Altri possono rilevare fasce orarie in qualsiasi momento.",
        "never": "Nessuno può rilevare la fascia oraria di qualcun altro."
      }
    }
  }
}
