// Generated by scripts/sync-planner-texts.mjs from the app's i18n (de.js). Do not edit:
// change the texts in the app, or override them in de.js next to this file.
export default {
  "common": {
    "add": "Hinzufügen",
    "apply": "Übernehmen",
    "back": "Zurück",
    "cancel": "Abbrechen",
    "change": "Ändern",
    "close": "Schliessen",
    "howItWorks": "So funktioniert’s",
    "loading": "Lädt …",
    "next": "Weiter",
    "undo": "Rückgängig"
  },
  "confirm": {
    "startOver": {
      "title": "Neu beginnen?",
      "text": "Alle Eingaben auf diesem Gerät werden gelöscht.",
      "ok": "Alles löschen"
    }
  },
  "setup": {
    "progress": "Fortschritt",
    "stepOf": "Schritt {n} von {total}",
    "steps": {
      "house": "Haus",
      "machines": "Waschküche",
      "times": "Zeiten",
      "plan": "Fester Plan",
      "rules": "Regeln",
      "account": "Zugang"
    },
    "savedLocally": "Deine Eingaben bleiben auf diesem Gerät, bis du das Haus erstellst.",
    "startOver": "Neu beginnen",
    "block": {
      "houseName": "Gib dem Haus einen Namen.",
      "flatNames": "Jede Wohnung braucht einen Namen.",
      "machines": "Wähle mindestens eine Maschine oder einen Raum.",
      "machineNames": "Alles braucht einen Namen.",
      "times": "Wähle mindestens einen Tag.",
      "timeErrors": "Bitte korrigiere die markierten Zeiten.",
      "name": "Gib deinen Namen ein.",
      "email": "Gib eine gültige E-Mail-Adresse ein.",
      "password": "Das Passwort braucht mindestens 8 Zeichen."
    },
    "house": {
      "title": "Willkommen! Erzähl uns von eurem Haus",
      "lead": "In sechs kurzen Schritten entsteht euer Waschplan. Du kannst alles später ändern.",
      "name": "Name des Hauses",
      "namePh": "z. B. Musterweg 12",
      "nameHint": "Steht oben im Plan und auf dem Aushang.",
      "flatsTitle": "Wohnungen",
      "count": "Wie viele Wohnungen teilen sich die Waschküche?",
      "names": "Wie heissen die Wohnungen?",
      "quickFill": "Schnell ausfüllen:",
      "fillNumbers": "Wohnung 1, 2, 3 …",
      "fillFloors2": "EG links, EG rechts …",
      "fillFloors1": "EG, 1. OG, 2. OG …",
      "colorLabel": "Farbe von {name}",
      "colorHint": "Tippe auf einen Punkt, um die Farbe der Wohnung im Plan zu ändern.",
      "flatN": "Wohnung {n}",
      "flatLabel": "Name von Wohnung {n}",
      "groundFloor": "EG",
      "floorN": "{n}. OG",
      "sides1": "",
      "sides2": "links,rechts",
      "sides3": "links,Mitte,rechts",
      "privacyTip": "Tipp: Verwende Bezeichnungen wie «2. OG links» statt Familiennamen. Der Plan kann auch auf einem Bildschirm in der Waschküche hängen.",
      "liveHere": "Wohnst du selbst in einer dieser Wohnungen?",
      "notLiving": "Nein, ich verwalte das Haus nur",
      "liveHereHint": "Dann kannst du auch für deine eigene Wohnung buchen."
    },
    "machines": {
      "title": "Was steht in eurer Waschküche?",
      "lead": "Zähle auf, was man buchen kann. Maschinen, die niemand bucht (z. B. ein Bügelbrett), musst du nicht angeben.",
      "example": {
        "washer": "Wäsche waschen",
        "dryer": "Wäschetrockner",
        "drying_room": "Raum zum Aufhängen",
        "other": "z. B. Bügelraum"
      },
      "howTitle": "Wie wird gebucht?",
      "together": "Alles zusammen",
      "togetherHint": "Wer dran ist, hat die ganze Waschküche mit allen Maschinen. Typisch bei einem festen Waschtag.",
      "separate": "Jede Maschine einzeln",
      "separateHint": "Jede Maschine und jeder Raum wird für sich gebucht. Mehrere Wohnungen können gleichzeitig waschen.",
      "mixed": "Gemischt",
      "mixedHint": "Du bestimmst, was zusammengehört. Zum Beispiel Waschmaschine und Tumbler zusammen, den Trockenraum einzeln.",
      "help1": "Beispiel «Alles zusammen»: Wohnung A hat am Montag die Waschmaschine, den Tumbler und den Trockenraum.",
      "help2": "Beispiel «Einzeln»: Wohnung A wäscht am Montagmorgen, während Wohnung B ihre Wäsche im Trockenraum aufhängt.",
      "namesTitle": "So heisst es im Plan",
      "togetherName": "Name im Plan",
      "mixedIntro": "Was die gleiche Nummer hat, wird zusammen gebucht.",
      "groupN": "Gruppe {n}",
      "groupOf": "Gruppe von {name}",
      "groupNameLabel": "Name von Gruppe {n}",
      "roomN": "Waschküche {n}",
      "previewTitle": "Das kann man buchen",
      "previewCount": "{n} Eintrag im Plan|{n} Einträge im Plan"
    },
    "times": {
      "title": "Wann darf gewaschen werden?",
      "lead": "Lege die Tage fest und teile den Tag in Zeitfenster. Ein Zeitfenster ist die Zeit, die eine Wohnung am Stück bucht.",
      "help1": "Halte dich an die Hausordnung. Oft ist Waschen von 7 bis 22 Uhr erlaubt und am Sonntag nicht.",
      "help2": "Kürzere Zeitfenster heissen: mehr Wohnungen kommen pro Tag dran. Ein ganzer Tag ist bequem, wenn es wenige Wohnungen hat.",
      "helpUnits": "Die Zeiten gelten für alles, was man buchen kann. Unter «Verwalten» kannst du später für jede Maschine eigene Zeiten festlegen."
    },
    "plan": {
      "title": "Wer wäscht wann?",
      "lead": "Im festen Plan hat jede Wohnung ihre Zeitfenster – so wie ein wiederkehrender Termin im Kalender. Was frei bleibt, kann jede Wohnung zusätzlich buchen.",
      "help1": "Wähle ein Zeitfenster, um es einer Wohnung zu geben: jede Woche, alle 2 Wochen oder einmal im Monat.",
      "help2": "Mehrere Wohnungen können sich ein Zeitfenster teilen, zum Beispiel abwechselnd jede zweite Woche.",
      "help3": "Rechts siehst du, wie viel Zeit jede Wohnung pro Monat bekommt. Wähle eine Wohnung, um ihre Termine zu sehen und für sie eine Zeit hinzuzufügen.",
      "suggested": "Wir haben einen fairen Vorschlag erstellt. Passe ihn an oder lass alles frei buchbar."
    }
  },
  "slots": {
    "days": "An welchen Tagen?",
    "closed": "geschlossen",
    "openingHours": "Von wann bis wann?",
    "from": "von",
    "to": "bis",
    "openingHint": "Die erste Wäsche beginnt frühestens, die letzte endet spätestens zu dieser Zeit.",
    "divisionTitle": "Wie wird der Tag aufgeteilt?",
    "division": {
      "day": "Ganzer Tag",
      "two": "2 Zeitfenster",
      "three": "3 Zeitfenster",
      "twoHours": "Alle 2 Stunden",
      "custom": "Eigene Zeiten"
    },
    "divisionHint": {
      "day": "Eine Wohnung pro Tag.",
      "two": "Vormittag und Nachmittag.",
      "three": "Morgen, Mittag, Abend.",
      "twoHours": "Viele kurze Zeitfenster.",
      "custom": "Du legst jedes Zeitfenster selbst fest."
    },
    "customTitle": "Zeitfenster",
    "perDayTitle": "Tag wählen",
    "perDaySwitch": "An einzelnen Tagen andere Zeiten (z. B. Samstag kürzer)",
    "differs": "Weicht vom ersten Tag ab",
    "copyToAll": "Zeiten von {day} für alle Tage übernehmen",
    "add": "Zeitfenster hinzufügen",
    "remove": "Zeitfenster entfernen",
    "previewTitle": "Vorschau: eine Woche",
    "summary": "{n} Zeitfenster pro Woche · {hours} Stunden",
    "fixErrors": "Bitte korrigiere die Zeiten.",
    "errorOrder": "Ein Zeitfenster muss enden, nachdem es beginnt.",
    "errorShort": "Ein Zeitfenster dauert mindestens 30 Minuten.",
    "errorOverlap": "Zwei Zeitfenster überschneiden sich."
  },
  "plan": {
    "free": "Frei",
    "mixed": "Je Maschine verschieden",
    "scope": "Für welche Maschine?",
    "scopeAll": "Alle gleich",
    "view": "Ansicht",
    "viewWeek": "Normale Woche",
    "viewCalendar": "Kalender",
    "calendarTitle": "Die nächsten Wochen",
    "clickHint": "Tippe auf ein Zeitfenster, um es zu ändern. Zum Verschieben ziehst du es auf ein anderes (am Handy: gedrückt halten und ziehen).",
    "mode": "Werkzeug",
    "modeEdit": "Bearbeiten",
    "modePaint": "Malen",
    "drop": {
      "move": "Loslassen zum Verschieben",
      "swap": "Loslassen zum Tauschen",
      "moved": "Verschoben",
      "swapped": "Getauscht"
    },
    "paint": {
      "brush": "Pinsel:",
      "free": "Frei",
      "hint": "Tippe auf Zeitfenster oder wische darüber: Sie gehen an «{name}». «Rückgängig» nimmt einen ganzen Strich zurück.",
      "everyOtherThis": "Alle 2 Wochen, ab dieser Woche",
      "everyOtherNext": "Alle 2 Wochen, ab nächster Woche"
    },
    "autoBtn": "Automatisch verteilen",
    "clearBtn": "Alles freigeben",
    "noSlots": "Es gibt noch keine Zeitfenster. Lege sie unter «Maschinen & Zeiten» fest.",
    "adminLead": "Welche Wohnung wann regelmässig waschen darf.",
    "adminHelp": "Änderungen gelten ab sofort für alle kommenden Wochen. Einzelne Buchungen der Bewohner:innen bleiben bestehen.",
    "stats": {
      "title": "Zeit pro Wohnung",
      "perMonth": "im Durchschnitt pro Monat",
      "days": "{n} Tage",
      "hours": "{n} Std.",
      "noTime": "keine feste Zeit",
      "highlight": "Termine dieser Wohnung zeigen und bearbeiten",
      "free": "Frei für alle: etwa {n} Zeitfenster pro Monat",
      "missing": "{names} hat noch keine feste Zeit.|{names} haben noch keine feste Zeit.",
      "uneven": "Die Zeit ist ungleich verteilt. Das ist in Ordnung, wenn es so abgemacht ist."
    },
    "party": {
      "none": "Diese Wohnung hat noch keine feste Zeit.",
      "remove": "Diesen Termin entfernen",
      "addTitle": "Zeit hinzufügen",
      "day": "Tag",
      "time": "Zeitfenster",
      "add": "Hinzufügen",
      "wholeDay": "Ganzer Tag",
      "added": "Hinzugefügt",
      "already": "Diese Wohnung hat dieses Zeitfenster schon so.",
      "taken": "Dieses Zeitfenster hat {name} schon mit derselben Wiederholung. Wähle eine andere Wiederholung oder ändere es in der Woche."
    },
    "dialog": {
      "intro": "Wer hat dieses Zeitfenster, und wie oft?",
      "mixed": "Die Maschinen haben hier unterschiedliche Einträge. Was du jetzt festlegst, gilt für alle. Einzelne Maschinen bearbeitest du oben unter «Für welche Maschine?».",
      "empty": "Dieses Zeitfenster ist frei. Wem soll es gehören?",
      "who": "Wohnung",
      "repeat": "Wiederholen",
      "startingOn": "Erstmals am",
      "onThe": "Im Monat am",
      "nthWeekday": "{nth} {day}",
      "remove": "Entfernen",
      "addParty": "Weitere Wohnung",
      "addPartyPh": "Wohnung wählen …",
      "addHint": "Mehrere Wohnungen wechseln sich ab, z. B. jede zweite Woche.",
      "duplicate": "Zwei Einträge haben dieselbe Regel. Bitte ändere einen davon.",
      "upcoming": "Die nächsten Termine",
      "instead": "Vorrang vor {names}",
      "clear": "Zeitfenster freigeben"
    },
    "auto": {
      "title": "Automatisch verteilen",
      "intro": "Die Zeitfenster werden reihum verteilt, beginnend mit dieser Woche. Danach kannst du alles einzeln anpassen.",
      "days": "Ganze Tage",
      "daysHint": "Jede Wohnung bekommt ganze Tage.",
      "slots": "Einzelne Zeitfenster",
      "slotsHint": "Jede Wohnung bekommt einzelne Zeitfenster.",
      "once": "Einmal pro Runde",
      "onceHint": "Der Rest bleibt frei für zusätzliche Buchungen.",
      "all": "So oft wie möglich",
      "allHint": "Alles wird gleichmässig verteilt.",
      "unit": {
        "days": "Tag|Tage",
        "slots": "Zeitfenster|Zeitfenster"
      },
      "eachWeekly": "Jede Wohnung bekommt {n} {unit} pro Woche.",
      "eachEveryN": "Jede Wohnung bekommt {n} {unit} alle {weeks} Wochen.",
      "freeWeekly": "{n} {unit} pro Woche bleibt frei für alle.|{n} {unit} pro Woche bleiben frei für alle.",
      "freeCycle": "In {weeks} Wochen bleibt {n} {unit} frei für alle.|In {weeks} Wochen bleiben {n} {unit} frei für alle.",
      "noneFree": "Es bleibt nichts frei.",
      "tooMany": "Es gibt zu wenige Zeitfenster, um alle Wohnungen reihum zu berücksichtigen. Füge mehr Tage oder Zeitfenster hinzu.",
      "replaces": "Das ersetzt den bisherigen Plan. Mit «Rückgängig» kannst du zurück.",
      "apply": "Verteilen"
    }
  },
  "rule": {
    "freq": {
      "weekly": "Jede Woche",
      "everyN": "Alle {n} Wochen",
      "monthly": "Einmal im Monat"
    },
    "nth": {
      "1": "1.",
      "2": "2.",
      "3": "3.",
      "4": "4.",
      "last": "letzten"
    },
    "short": {
      "everyN": "alle {n} Wo.",
      "monthly": {
        "1": "1. im Monat",
        "2": "2. im Monat",
        "3": "3. im Monat",
        "4": "4. im Monat",
        "last": "letzter im Monat"
      }
    },
    "long": {
      "weekly": "Jeden {day}",
      "everyOther": "Jeden zweiten {day}",
      "everyN": "Alle {n} Wochen am {day}",
      "monthly": {
        "1": "Am ersten {day} im Monat",
        "2": "Am zweiten {day} im Monat",
        "3": "Am dritten {day} im Monat",
        "4": "Am vierten {day} im Monat",
        "last": "Am letzten {day} im Monat"
      }
    }
  },
  "kind": {
    "washer": "Waschmaschine",
    "dryer": "Tumbler",
    "drying_room": "Trockenraum",
    "other": "Sonstiges",
    "laundry_room": "Waschküche",
    "plural": {
      "washer": "Waschmaschinen",
      "dryer": "Tumbler",
      "drying_room": "Trockenräume",
      "other": "Sonstiges"
    }
  },
  "print": {
    "lead": "Zwei Wochen pro A4-Seite, zum Aufhängen in der Waschküche. Änderst du etwas, druckst du einfach neu.",
    "from": "Ab Woche",
    "pages": "Umfang",
    "pagesOpt": "{n} Seite · {weeks} Wochen|{n} Seiten · {weeks} Wochen",
    "orientation": "Ausrichtung",
    "portrait": "Hochformat",
    "landscape": "Querformat",
    "machines": "Maschinen und Räume",
    "print": "Drucken",
    "pdfHint": "Im Druckfenster kannst du auch «Als PDF speichern» wählen.",
    "week": "KW {n}",
    "time": "Zeit",
    "free": "frei",
    "footer": "Erstellt mit Waschplaner · waschplaner.com",
    "printed": "Stand {date}",
    "welcomeTitle": "Euer Plan ist bereit!",
    "welcomeText": "Druck ihn aus und häng ihn in die Waschküche. Änderst du später etwas, druckst du einfach neu.",
    "none": "Wähle mindestens eine Maschine oder einen Raum."
  },
  "rules": {
    "weeks": "{n} Woche|{n} Wochen",
    "days": "{n} Tag|{n} Tage",
    "threeMonths": "3 Monate",
    "unit": {
      "days": "Tag|Tage",
      "slots": "Zeitfenster|Zeitfenster"
    },
    "sum": {
      "quota": "Jede Wohnung darf pro Woche {n} {unit} zusätzlich buchen.",
      "unlimited": "Jede Wohnung darf beliebig viele freie Zeitfenster zusätzlich buchen.",
      "none": "Zusätzliche Buchungen sind nicht möglich.",
      "horizon": "Gebucht wird höchstens {time} im Voraus.",
      "override": {
        "unused_after_grace": "Wird ein Zeitfenster {n} Minuten nach Beginn nicht genutzt, dürfen andere es übernehmen.",
        "anytime": "Andere dürfen fremde Zeitfenster jederzeit übernehmen.",
        "never": "Fremde Zeitfenster kann niemand übernehmen."
      }
    }
  }
}
