// The planner's texts: the ones shared with the app (app.<lang>.js, generated by
// scripts/sync-planner-texts.mjs) with the planner's own on top (<lang>.js).
import appDe from './app.de'
import appEn from './app.en'
import appFr from './app.fr'
import appIt from './app.it'
import de from './de'
import en from './en'
import fr from './fr'
import it from './it'

const merge = (base, over) =>
  Object.fromEntries(
    [...new Set([...Object.keys(base), ...Object.keys(over)])].map((k) => {
      const [a, b] = [base[k], over[k]]
      return [k, a && b && typeof a === 'object' && typeof b === 'object' ? merge(a, b) : b ?? a]
    }),
  )

export default { de: merge(appDe, de), en: merge(appEn, en), fr: merge(appFr, fr), it: merge(appIt, it) }
