// Help pages in Italian. Same slugs and blocks as docs.de.js. The app is in German
// and English, so buttons are quoted with their English label, «Book».
export default [
  {
    slug: 'setup',
    section: 'use',
    icon: 'wand',
    title: 'Configurare uno stabile',
    summary: 'La procedura guidata in sei passi, e cosa viene dopo.',
    blocks: [
      { p: 'La procedura guidata ti chiede in sei brevi passi tutto ciò che serve al piano. Quello che inserisci resta su questo dispositivo (senza la password) fino all’ultimo passo, che crea lo stabile. Puoi cambiare tutto in seguito.' },
      { callout: 'Ospitato da noi: apri [{app}/setup]({app}/setup). Self-hosting: apri l’indirizzo del tuo server e tocca «Set one up – it takes 5 minutes».', tone: 'tip' },
      { h2: 'I sei passi' },
      {
        steps: [
          { title: 'Stabile', text: 'Il nome dello stabile e gli appartamenti. «Quick fill» crea nomi come «PT sinistra, PT destra, 1° sinistra». Tocca un punto per cambiare il colore di un appartamento.' },
          { title: 'Lavanderia', text: 'Quante lavatrici, asciugatrici e locali di asciugatura ci sono, e come si prenotano: **tutto insieme** (una lavanderia per prenotazione), **ogni macchina separatamente** o **in modo misto**, per esempio lavatrice e asciugatrice insieme, il locale di asciugatura a parte.' },
          { title: 'Orari', text: 'I giorni di bucato e come una giornata è divisa in fasce orarie: giornata intera, 2 o 3 fasce, ogni 2 ore o orari tuoi, se serve diversi in alcuni giorni. Una vista della settimana mostra il risultato.' },
          { title: 'Turni fissi', text: 'Chi ha quale fascia regolarmente, come appuntamenti ricorrenti: ogni settimana, ogni 2–4 settimane o una volta al mese (p. es. il primo o l’ultimo martedì del mese). La procedura propone una distribuzione equa; un calendario mensile e il «Time per flat» mostrano il risultato.' },
          { title: 'Regole', text: 'Quante prenotazioni extra sono permesse, con quanto anticipo, e cosa succede alle fasce non usate. Un riassunto in parole semplici mostra cosa vale.' },
          { title: 'Accesso', text: 'Nome, e-mail e password dell’amministrazione. Scegli anche **Gratis** (da stampare) o **Plus** ({trial} giorni in regalo, senza dati di pagamento) e vedi un riassunto di tutto.' },
        ],
      },
      { callout: 'Usa nomi come «2° sinistra» invece dei cognomi. Il piano è appeso in lavanderia, e con Plus tutto lo stabile lo vede online.', tone: 'privacy' },
      { h2: 'Poi: stampare o invitare' },
      {
        list: [
          '**Gratis:** stampa il piano sotto «Manage → Print»: due settimane per pagina A4, per ogni macchina o locale, fino a {printFree} settimane alla volta (con Plus un anno intero). La finestra di stampa può anche salvarlo in PDF. Cambi qualcosa in seguito? Basta ristampare.',
          '**Plus:** la pagina «Invite» spiega i passi successivi: stampare l’avviso con il codice QR e appenderlo in lavanderia, e dare a ogni appartamento il suo codice di accesso a 6 cifre. Le carte con il proprio codice QR lo compilano automaticamente.',
          '**Self-hosting con un solo stabile?** Imposta poi `ALLOW_SIGNUP=false`, così nessuno crea altri stabili.',
        ],
      },
    ],
  },
  {
    slug: 'residents',
    section: 'use',
    icon: 'users',
    title: 'Per i residenti',
    summary: 'Unirsi, prenotare, liberare: il piano ogni giorno.',
    blocks: [
      { callout: 'Usate il piano online quando il vostro stabile ha [Plus](/pricing). Altrimenti è appeso su carta in lavanderia, e l’app mostra «The online schedule is paused».' },
      { h2: 'Unirsi' },
      {
        steps: [
          { title: 'Scansiona il codice QR', text: 'Quello dell’avviso in lavanderia o della carta del tuo appartamento.' },
          { title: 'Scegli l’appartamento', text: 'E inserisci il codice di accesso a 6 cifre. Con la carta del tuo appartamento è già compilato.' },
          { title: 'Fatto', text: 'Resti connesso su questo dispositivo. Con e-mail e password puoi accedere anche da altri dispositivi – se vuoi.' },
        ],
      },
      { h2: 'Il piano' },
      { p: 'Ogni colore è un appartamento. Le fasce del tuo appartamento hanno un bordo spesso e l’icona di una persona. Sugli schermi grandi vedi tutta la settimana, sul telefono un giorno alla volta. Tocca il titolo della settimana per andare a un giorno qualsiasi.' },
      { h2: 'Cosa puoi fare' },
      {
        table: {
          head: ['Azione', 'Come'],
          rows: [
            ['**Prenotare** («Book»)', 'Tocca una fascia libera e conferma. Fuori dai tuoi turni fissi è una prenotazione extra; l’amministrazione decide quante sono permesse a settimana.'],
            ['**Liberare** («Free up»)', 'Non ti serve la tua fascia? Liberala, così altri possono prenotarla. Finché nessuno la prenota, puoi riprenderla.'],
            ['**Modificare** («Edit»)', 'Aggiungere una nota («bucato a 60°») o usare solo una parte del tempo, così gli altri vedono quando è libero.'],
            ['**Spostare** («Move»)', 'Trascina la tua fascia su una libera. Oppure toccala, poi «Move» e una fascia libera.'],
            ['**Check-in** («Check in»)', 'Tocca «Check in» quando sei in lavanderia. Così nessuno può subentrare nella tua fascia.'],
            ['**Finito – libera il resto** («Done – free the rest»)', 'Finito prima? Da subito ogni appartamento può prenotare il resto, senza che conti come prenotazione extra. «Not done yet» lo annulla finché nessuno ha prenotato.'],
            ['**Subentrare** («Take over»)', 'Prendere la fascia non usata di un altro appartamento: secondo il regolamento dopo un tempo d’attesa, in qualsiasi momento o mai. L’altro appartamento viene avvisato.'],
          ],
        },
      },
      { h2: 'La tua pagina («My laundry»)' },
      { p: 'Sotto «My laundry» vedi cosa viene dopo, i turni fissi del tuo appartamento («Every other Tuesday, 07:00–17:00») e le tue notifiche. Lì scegli se ricevere anche via e-mail le modifiche alle tue fasce, ti abboni al calendario e imposti la dimensione del testo.' },
      { callout: 'Chi ha l’indirizzo dell’abbonamento al calendario vede gli orari del tuo appartamento. Condividilo solo con chi vive con te.', tone: 'privacy' },
      { h2: 'Come app sul telefono' },
      {
        list: [
          '**Android e computer:** sotto «My laundry → As an app», tocca «Install as an app».',
          '**iPhone e iPad:** in Safari tocca «Condividi» e poi «Aggiungi alla schermata Home».',
          'Poi il piano si apre anche senza internet e mostra l’ultimo stato caricato. Prenotare funziona di nuovo appena sei online.',
        ],
      },
      { h2: 'Quando Plus è finito' },
      { p: 'Puoi ancora vedere il piano per {view} giorni, ma non prenotare né modificare nulla. Poi torna appeso su carta in lavanderia – finché l’amministrazione non ricompra Plus.' },
    ],
  },
  {
    slug: 'admin',
    section: 'use',
    icon: 'sliders',
    title: 'Per l’amministrazione',
    summary: 'Turni fissi, stampa, macchine, regole, appartamenti e Plus.',
    blocks: [
      { p: 'Sotto «Manage» modifichi tutto ciò che hai configurato nella procedura guidata. Le modifiche si raccolgono in una barra in basso che dice cosa cambia («2 time slots changed · 1 new»). Valgono solo dopo «Save». Ciò che non si può annullare chiede prima conferma e ne indica le conseguenze.' },
      { h2: 'Le sezioni' },
      {
        table: {
          head: ['Sezione', 'Cosa ci fai'],
          rows: [
            ['**Regular schedule**', 'Chi ha quale fascia regolarmente. Lo stesso editor della procedura guidata, con calendario mensile e «Time per flat». Trascina le fasce (per spostarle o scambiarle), oppure «dipingi»: scegli un appartamento, poi tocca o scorri sulle fasce.'],
            ['**Machines & times**', 'Macchine e locali, le loro fasce per giorno e come si prenotano. Una lavanderia si può dividere nelle sue macchine e riunire di nuovo; orari, turni fissi e prenotazioni restano.'],
            ['**Rules** · Plus', 'Prenotazioni extra a settimana (contate in fasce o in giorni), con quanto anticipo si può prenotare e quando altri possono subentrare.'],
            ['**Print**', 'Due settimane per pagina A4, a partire dalla settimana che scegli, per le macchine e i locali scelti: con Gratis fino a {printFree} settimane alla volta, con Plus un anno intero. La finestra di stampa può anche salvare in PDF.'],
            ['**Invite** · Plus', 'Stampare l’avviso con il codice QR e condividere o rinnovare il link di invito.'],
            ['**Flats**', 'Nomi, colori e codici di accesso. Un nuovo codice invalida la vecchia carta; chi è già connesso resta connesso.'],
            ['**People** · Plus', 'Chi appartiene a quale appartamento. Rimuovere persone.'],
            ['**Activity** · Plus', 'Chi ha prenotato, liberato o modificato cosa, e quando.'],
            ['**Settings**', 'Nome, fuso orario e lingua dello stabile, se ci si può unire con il codice QR e se esiste una vista pubblica del piano.'],
            ['**Plus**', 'Provare, comprare o rinnovare Plus, e vedere i pagamenti passati.'],
          ],
        },
      },
      { p: 'Con Gratis, le sezioni che fanno parte di Plus sono visibili, ma inattive e segnate come Plus.' },
      { h2: 'Gestire Plus' },
      {
        list: [
          '**Provare:** ogni stabile può usare Plus gratis per {trial} giorni, una volta, senza dati di pagamento – all’ultimo passo della configurazione o con l’offerta sotto «Manage». {trialRemind} giorni prima della fine arriva un’e-mail.',
          '**Comprare:** sotto «Manage → Plus», per un anno, sulla pagina di pagamento sicura di Stripe. Si paga per appartamento attivo. Se compri durante la prova, l’anno inizia solo quando finisce.',
          '**Rinnovare:** negli ultimi {renew} giorni; il nuovo anno inizia quando finisce quello vecchio. Ti avvisiamo via e-mail {remind} giorni prima della fine. Nulla si rinnova da sé.',
          '**Un nuovo appartamento durante l’anno:** la pagina «Flats» lo chiede e apre la pagina di pagamento per la sua quota fino alla fine dell’anno (almeno CHF {min}). L’appartamento inizia una volta pagato; nessun altro se ne accorge.',
          '**Quando Plus finisce:** i residenti possono ancora vedere il piano per {view} giorni. Poi lo stabile torna a Gratis: continui a modificare e stampare il piano, e tutto resta salvato.',
        ],
      },
      { h2: 'Regole per subentrare' },
      {
        list: [
          '**Dopo il tempo d’attesa** (predefinito): solo quando la fascia è iniziata e il tempo d’attesa è passato, e solo se nessuno ha fatto il check-in.',
          '**In qualsiasi momento**, finché nessuno ha fatto il check-in.',
          '**Mai:** non si può subentrare nelle fasce degli altri.',
        ],
      },
      { p: 'L’appartamento interessato riceve una notifica nell’app e, se l’ha scelto, un’e-mail.' },
      { h2: 'Quando i turni fissi si sovrappongono' },
      { p: 'Se due turni fissi valgono per la stessa fascia, vince quello che si ripete meno spesso. Così funziona «ogni lunedì l’appartamento A, ma il primo lunedì del mese l’appartamento B».' },
      { h2: 'Vista pubblica del piano' },
      { p: 'Per uno schermo in lavanderia esiste una vista senza accesso, senza note e senza nomi di persone. Si aggiorna ogni minuto. La attivi sotto «Settings»; fa parte di Plus.' },
    ],
  },
  {
    slug: 'self-hosting',
    section: 'run',
    icon: 'server',
    title: 'Self-hosting',
    summary: 'Far girare Waschplaner sul tuo server con Docker.',
    blocks: [
      { p: 'Waschplaner è composto da tre container: il database (PostgreSQL 17), il server (Go) e l’interfaccia web (nginx). Docker Compose li avvia insieme. In self-hosting hai tutte le funzioni, e Plus non costa nulla se non configuri i pagamenti.' },
      { h2: 'Cosa ti serve' },
      {
        list: [
          'Un server Linux, un mini PC o un NAS con **Docker** e **Docker Compose**.',
          'Un **indirizzo** (dominio o sottodominio), così i residenti raggiungono il piano via HTTPS.',
          'Facoltativo: un **server di posta** (SMTP) per le notifiche via e-mail e «password dimenticata».',
        ],
      },
      { h2: 'Avvio rapido' },
      { p: 'Per provarlo sul tuo computer:' },
      { code: 'git clone {repo}.git waschplaner\ncd waschplaner\ndocker compose up -d --build' },
      { p: 'Poi apri [http://localhost:8080](http://localhost:8080) e tocca «Set one up – it takes 5 minutes». Il database viene creato e aggiornato automaticamente all’avvio.' },
      { h2: 'In produzione' },
      {
        steps: [
          { title: 'Crea le impostazioni', text: 'Copia il modello e genera una password sicura per il database:', code: 'cp .env.example .env\nopenssl rand -base64 32' },
          { title: 'Imposta i valori importanti', text: '`POSTGRES_PASSWORD` con la password generata, `PUBLIC_URL` con il tuo indirizzo (p. es. `https://bucato.example.ch`), `COOKIE_SECURE=true` appena HTTPS funziona, e `FAKE_STRIPE=false` per Plus senza pagamenti. Tutti i valori sono descritti in [Configurazione](/docs/configuration).' },
          { title: 'Avvia', code: 'docker compose up -d --build' },
        ],
      },
      { h2: 'Plus e pagamenti' },
      { p: '`docker-compose.yml` imposta `FAKE_STRIPE=true`. Plus viene allora «pagato» su una pagina di pagamento simulata, in modalità test e senza denaro vero, così puoi provare tutto. In produzione scegli una delle due vie:' },
      {
        list: [
          '**Senza pagamenti**, p. es. solo per il tuo stabile: `FAKE_STRIPE=false` e `STRIPE_SECRET_KEY` vuota. Allora attivi semplicemente Plus sotto «Manage → Plus», gratis.',
          '**Con pagamenti tramite Stripe:** metti la tua chiave in `STRIPE_SECRET_KEY`. Prova prima con una chiave di test (`sk_test_…`) e la carta di test 4242 4242 4242 4242; i pagamenti di test non contano più appena è impostata una chiave vera. Una chiave ha sempre la precedenza su `FAKE_STRIPE`.',
        ],
      },
      { code: 'FAKE_STRIPE=false\nSTRIPE_SECRET_KEY=sk_test_…\nSTRIPE_WEBHOOK_SECRET=whsec_…\nSTRIPE_PAYMENT_METHODS=card,twint\nPLUS_PRICE=2\nPLUS_CURRENCY=CHF', title: '.env' },
      { p: 'Consigliato: nella dashboard di Stripe, sotto «Developers → Webhooks», aggiungi un webhook verso `https://<il tuo indirizzo>/api/stripe/webhook` con gli eventi `checkout.session.completed` e `checkout.session.async_payment_succeeded`, e metti il suo segreto di firma in `STRIPE_WEBHOOK_SECRET`. Così i pagamenti contano anche se qualcuno chiude la pagina di pagamento prima di tornare.' },
      { callout: 'Waschplaner non invia ricevute. Attiva le e-mail per i pagamenti riusciti nella dashboard di Stripe. TWINT richiede la valuta CHF e va attivato nella dashboard.', tone: 'tip' },
      { h2: 'HTTPS con Caddy' },
      { p: 'L’interfaccia web ascolta sulla porta 8080, senza cifratura. Un reverse proxy davanti si occupa di HTTPS. Con [Caddy](https://caddyserver.com) basta questo file; Caddy ottiene il certificato da solo:' },
      { code: 'bucato.example.ch {\n\treverse_proxy localhost:8080\n}', title: 'Caddyfile' },
      { callout: 'Imposta `HTTP_PORT=127.0.0.1:8080`, così solo Caddy raggiunge la porta 8080. E non dimenticare `COOKIE_SECURE=true` e `PUBLIC_URL=https://…`: l’indirizzo compare nelle e-mail, nei link del calendario e di invito, e la pagina di pagamento ci ritorna.', tone: 'warn' },
      { h2: 'Solo il tuo stabile' },
      { p: 'Dopo aver creato il tuo stabile, imposta `ALLOW_SIGNUP=false` e riavvia. Così nessun altro può creare uno stabile sul tuo server.' },
      { h2: 'E-mail' },
      { p: 'Senza server di posta ci sono solo notifiche nell’app, e «password dimenticata» non funziona. Le e-mail ai residenti fanno parte di Plus. Inserisci i dati del tuo fornitore di posta:' },
      { code: 'SMTP_HOST=smtp.example.ch\nSMTP_PORT=587\nSMTP_USER=bucato@example.ch\nSMTP_PASSWORD=…\nSMTP_FROM=Waschplaner <bucato@example.ch>', title: '.env' },
      { h2: 'Protezione dallo spam' },
      { p: 'Facoltativamente, Google reCAPTCHA protegge i moduli pubblici: accesso, creazione di uno stabile, adesione a uno stabile e password dimenticata. È disattivato finché non sono impostate entrambe le chiavi.' },
      { callout: 'Con reCAPTCHA il browser carica uno script di Google su queste pagine. Menzionalo nella tua informativa sulla protezione dei dati.', tone: 'privacy' },
      { h2: 'Backup' },
      { p: 'Tutti i dati sono nel database. Così li salvi in un file:' },
      { code: 'docker compose exec -T db sh -c \'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"\' | gzip > waschplaner-$(date +%F).sql.gz' },
      { p: 'E così li ripristini in un database vuoto:' },
      { code: 'gunzip -c waschplaner-2026-09-23.sql.gz | docker compose exec -T db sh -c \'psql -U "$POSTGRES_USER" "$POSTGRES_DB"\'' },
      { callout: 'Imposta un cron job giornaliero e conserva alcuni backup in un altro luogo.', tone: 'tip' },
      { h2: 'Aggiornare' },
      { code: 'git pull\ndocker compose up -d --build' },
      { p: 'Le modifiche al database si eseguono automaticamente all’avvio del server. Fai prima un backup.' },
      { h2: 'Contribuire' },
      { p: 'Come avviare Waschplaner senza Docker, eseguire i test e orientarti nel codice: trovi tutto nel [README]({repo}#readme) (in inglese).' },
    ],
  },
  {
    slug: 'configuration',
    section: 'run',
    icon: 'terminal',
    title: 'Configurazione',
    summary: 'Tutte le impostazioni per il tuo server.',
    blocks: [
      { p: 'Docker Compose legge il file `.env` nella cartella del progetto. Dopo una modifica, `docker compose up -d` applica i nuovi valori. «Predefinito» è il valore in `docker-compose.yml`.' },
      { h2: 'Base' },
      {
        table: {
          head: ['Variabile', 'Predefinito', 'Significato'],
          rows: [
            ['`POSTGRES_PASSWORD`', '`waschplan`', 'La password del database. **Da cambiare assolutamente in produzione.**'],
            ['`POSTGRES_USER`', '`waschplan`', 'Il nome utente del database.'],
            ['`POSTGRES_DB`', '`waschplan`', 'Il nome del database.'],
            ['`HTTP_PORT`', '`8080`', 'La porta sul server. `127.0.0.1:8080` la rende raggiungibile solo in locale, p. es. dietro un reverse proxy.'],
            ['`PUBLIC_URL`', '`http://localhost:8080`', 'L’indirizzo a cui i residenti aprono Waschplaner. Compare nelle e-mail, nei link del calendario e di invito, e protegge i moduli (CSRF).'],
            ['`COOKIE_SECURE`', '`false`', '`true` appena Waschplaner funziona via HTTPS.'],
            ['`ALLOW_SIGNUP`', '`true`', '`false` perché nessuno possa creare altri stabili.'],
          ],
        },
      },
      { h2: 'Plus e pagamenti' },
      {
        table: {
          head: ['Variabile', 'Predefinito', 'Significato'],
          rows: [
            ['`PLUS_PRICE`', '`2`', 'Il prezzo per appartamento all’anno, p. es. `1` o `4.50`.'],
            ['`PLUS_CURRENCY`', '`CHF`', 'La valuta come codice, p. es. `CHF` o `EUR`. Solo valute con due decimali.'],
            ['`FAKE_STRIPE`', '`true`', 'Una pagina di pagamento simulata in modalità test; non viene addebitato nulla. `false` e nessuna chiave: Plus è un interruttore gratuito.'],
            ['`STRIPE_SECRET_KEY`', '–', 'Chiave Stripe: `sk_test_…` per la modalità test, `sk_live_…` per i pagamenti veri. Ha la precedenza su `FAKE_STRIPE`.'],
            ['`STRIPE_WEBHOOK_SECRET`', '–', 'Il segreto di firma del webhook. Conferma i pagamenti anche se nessuno torna dalla pagina di pagamento.'],
            ['`STRIPE_PAYMENT_METHODS`', '–', 'Metodi di pagamento, p. es. `card,twint`. Vuoto: ciò che è attivato nella dashboard di Stripe.'],
          ],
        },
      },
      { h2: 'E-mail' },
      {
        table: {
          head: ['Variabile', 'Predefinito', 'Significato'],
          rows: [
            ['`SMTP_HOST`', '–', 'Il server di posta. Vuoto: solo notifiche nell’app.'],
            ['`SMTP_PORT`', '`587`', 'La porta del server di posta.'],
            ['`SMTP_USER`', '–', 'Nome utente presso il server di posta.'],
            ['`SMTP_PASSWORD`', '–', 'Password presso il server di posta.'],
            ['`SMTP_FROM`', '`Waschplaner <noreply@example.com>`', 'Il mittente delle e-mail.'],
          ],
        },
      },
      { h2: 'reCAPTCHA' },
      {
        table: {
          head: ['Variabile', 'Predefinito', 'Significato'],
          rows: [
            ['`RECAPTCHA_SITE_KEY`', '–', 'La chiave pubblica di Google. reCAPTCHA è attivo solo se sono impostate entrambe le chiavi.'],
            ['`RECAPTCHA_SECRET`', '–', 'La chiave segreta di Google.'],
            ['`RECAPTCHA_VERSION`', '`v2`', '`v2`: la casella «Non sono un robot». `v3`: invisibile, con un punteggio.'],
            ['`RECAPTCHA_MIN_SCORE`', '`0.5`', 'Solo con `v3`: il punteggio minimo accettato, da 0 a 1.'],
          ],
        },
      },
      { h2: 'Avanzate' },
      { p: 'Questi valori non sono in `.env`. Per cambiarli, modificali o aggiungili in `docker-compose.yml` sotto `api` → `environment`.' },
      {
        table: {
          head: ['Variabile', 'Predefinito', 'Significato'],
          rows: [
            ['`DATABASE_URL`', 'da `POSTGRES_*`', 'La connessione al database.'],
            ['`LISTEN_ADDR`', '`:8080`', 'L’indirizzo su cui il server ascolta nel container.'],
            ['`TRUST_PROXY`', '`true`', 'Prendere l’indirizzo dei visitatori da `X-Forwarded-For`. Importante per limitare i tentativi di accesso.'],
            ['`AUTH_RATE_LIMIT`', '`10`', 'Quanti accessi, registrazioni e adesioni un indirizzo può tentare al minuto.'],
            ['`MAIL_LOG`', '`false`', '`true`: scrivere le e-mail nel log invece di inviarle, per lo sviluppo.'],
          ],
        },
      },
    ],
  },
  {
    slug: 'glossary',
    section: 'more',
    icon: 'book',
    title: 'Glossario',
    summary: 'Le parole di Waschplaner, in tedesco e in inglese, con il loro significato in italiano.',
    blocks: [
      { p: 'L’app è in tedesco e in inglese. Ecco le sue parole nelle due lingue, con quello che significano.' },
      {
        table: {
          head: ['Deutsch', 'English', 'Significato'],
          rows: [
            ['Plan', 'Schedule', 'Il piano: la vista della settimana che vedono tutti.'],
            ['Fester Plan, feste Zeit', 'Regular schedule, regular time', 'I turni fissi: chi ha quale fascia regolarmente, come un appuntamento ricorrente.'],
            ['Zeitfenster', 'Time slot', 'La fascia oraria: il tempo che un appartamento prenota in una volta, p. es. 07:00–12:00.'],
            ['Buchen', 'Book', 'Prenotare una fascia libera.'],
            ['Zusätzlich', 'Extra', 'Una prenotazione extra, fuori dai propri turni fissi; limitata a settimana.'],
            ['Freigeben', 'Free up', 'Liberare una fascia, così altri possono prenotarla.'],
            ['Übernehmen', 'Take over', 'Subentrare nella fascia non usata di un altro appartamento, che viene avvisato.'],
            ['Fertig – Rest freigeben', 'Done – free the rest', 'Finito prima: il resto della fascia in corso è libero per tutti.'],
            ['Rest buchen', 'Book the rest', 'Prenotare il resto di una fascia che un altro appartamento ha finito prima. Mai una prenotazione extra.'],
            ['Einchecken', 'Check in', '«Sono in lavanderia.» Protegge la fascia.'],
            ['Meine Wäsche', 'My laundry', 'La tua pagina: prossime fasce, turni fissi, notifiche.'],
            ['Haus', 'House', 'Lo stabile, con il suo piano e le sue regole.'],
            ['Wohnung', 'Flat', 'L’appartamento, un’economia domestica. Le prenotazioni appartengono agli appartamenti.'],
            ['Bewohner:in', 'Resident', 'Residente: chi si è unito allo stabile con il codice di accesso di un appartamento.'],
            ['Verwaltung', 'Administrator', 'L’amministrazione: chi configura e gestisce il piano.'],
            ['Waschküche', 'Laundry room', 'La lavanderia: più macchine prenotate insieme.'],
            ['Maschine', 'Machine', 'Lavatrice, asciugatrice o locale di asciugatura.'],
            ['Zugangscode', 'Access code', 'Il codice di accesso: le 6 cifre sulla carta di un appartamento, per unirsi allo stabile.'],
            ['Aushang', 'Poster', 'L’avviso stampato con il codice QR dello stabile.'],
            ['Gratis', 'Free', 'Gratis: il piano senza Plus, che l’amministrazione crea e stampa, fino a {printFree} settimane alla volta.'],
            ['Plus', 'Plus', 'Tutti usano il piano online, con e-mail, abbonamento al calendario e vista pubblica.'],
            ['Öffentliche Plan-Ansicht', 'Public schedule view', 'La vista pubblica: il piano senza accesso, per uno schermo in lavanderia.'],
            ['Kaufen, verlängern', 'Buy, renew', 'Comprare un anno di Plus; rinnovare aggiunge un anno.'],
            ['Bezahlseite', 'Payment page', 'La pagina di Stripe dove l’amministrazione paga.'],
          ],
        },
      },
    ],
  },
]
