// Help pages in German. Each page is a list of blocks, drawn by DocBlocks.vue:
// { h2 }, { p }, { list }, { steps: [{ title, text?, code? }] }, { code, title? },
// { callout, tone? }, { table: { head, rows } }. Texts use the inline markup
// (**bold**, `code`, [label](url)) and {app}, {repo}, {email}.
export default [
  {
    slug: 'setup',
    section: 'use',
    icon: 'wand',
    title: 'Haus einrichten',
    summary: 'Der Assistent in sechs Schritten, und was danach kommt.',
    blocks: [
      { p: 'Der Assistent fragt in sechs kurzen Schritten alles ab, was der Plan braucht. Deine Eingaben bleiben auf diesem Gerät (ohne Passwort), bis du im letzten Schritt das Haus erstellst. Du kannst alles später ändern.' },
      { callout: 'Gehostet: Öffne [{app}/setup]({app}/setup). Selbst betrieben: Öffne die Adresse deines Servers und tippe auf «Jetzt einrichten».', tone: 'tip' },
      { h2: 'Die sechs Schritte' },
      {
        steps: [
          { title: 'Haus', text: 'Der Name des Hauses und die Wohnungen. «Schnell ausfüllen» erstellt Bezeichnungen wie «EG links, EG rechts, 1. OG links». Tippe auf einen Punkt, um die Farbe einer Wohnung zu ändern.' },
          { title: 'Waschküche', text: 'Wie viele Waschmaschinen, Tumbler und Trockenräume es gibt, und wie gebucht wird: **alles zusammen** (eine Waschküche pro Buchung), **jede Maschine einzeln** oder **gemischt**, z. B. Waschmaschine und Tumbler zusammen, den Trockenraum einzeln.' },
          { title: 'Zeiten', text: 'An welchen Tagen gewaschen wird und wie ein Tag in Zeitfenster aufgeteilt ist: ganzer Tag, 2 oder 3 Zeitfenster, alle 2 Stunden oder eigene Zeiten, auf Wunsch an einzelnen Tagen anders. Eine Wochenansicht zeigt das Ergebnis.' },
          { title: 'Fester Plan', text: 'Wer welches Zeitfenster regelmässig hat, wie wiederkehrende Termine: jede Woche, alle 2–4 Wochen oder einmal im Monat (1.–4. oder letzter Wochentag). Der Assistent schlägt eine faire Verteilung vor; ein Monatskalender und die «Zeit pro Wohnung» zeigen das Ergebnis.' },
          { title: 'Regeln', text: 'Wie viel zusätzlich gebucht werden darf, wie weit im Voraus, und was mit nicht genutzten Zeitfenstern passiert. Eine Zusammenfassung in einfachen Worten zeigt, was gilt.' },
          { title: 'Zugang', text: 'Vorname, E-Mail und Passwort für die Verwaltung, dazu eine Zusammenfassung von allem. Danach ist der Plan bereit.' },
        ],
      },
      { callout: 'Verwende Bezeichnungen wie «2. OG links» statt Familiennamen. Der Plan ist für alle im Haus sichtbar.', tone: 'privacy' },
      { h2: 'Danach: Bewohner:innen einladen' },
      { p: 'Die Seite «Einladen» erklärt die nächsten Schritte:' },
      {
        list: [
          '**Aushang drucken** und in der Waschküche aufhängen. Der QR-Code darauf führt zum Plan des Hauses.',
          '**Zugangscodes verteilen:** Jede Wohnung hat einen 6-stelligen Code. Die Karten mit eigenem QR-Code füllen ihn automatisch aus.',
          '**Selbst betrieben und nur ein Haus?** Setze danach `ALLOW_SIGNUP=false`, damit niemand weitere Häuser anlegt.',
        ],
      },
    ],
  },
  {
    slug: 'residents',
    section: 'use',
    icon: 'users',
    title: 'Für Bewohner:innen',
    summary: 'Beitreten, buchen, freigeben: der Plan im Alltag.',
    blocks: [
      { h2: 'Beitreten' },
      {
        steps: [
          { title: 'QR-Code scannen', text: 'Den Code auf dem Aushang in der Waschküche oder auf der Karte deiner Wohnung.' },
          { title: 'Wohnung wählen', text: 'Und den 6-stelligen Zugangscode eingeben. Mit der Karte deiner Wohnung ist er schon ausgefüllt.' },
          { title: 'Fertig', text: 'Du bleibst auf diesem Gerät angemeldet. Mit E-Mail und Passwort kannst du dich auch auf anderen Geräten anmelden – freiwillig.' },
        ],
      },
      { h2: 'Der Plan' },
      { p: 'Jede Farbe steht für eine Wohnung. Die Zeitfenster deiner Wohnung sind dick umrandet und mit einer Person markiert. Auf breiten Bildschirmen siehst du die ganze Woche, auf dem Handy einen Tag nach dem anderen. Tippe auf den Wochentitel, um zu einem beliebigen Tag zu springen.' },
      { h2: 'Was du tun kannst' },
      {
        table: {
          head: ['Aktion', 'So geht’s'],
          rows: [
            ['**Buchen**', 'Tippe auf ein freies Zeitfenster und bestätige. Ausserhalb deiner festen Zeiten ist das eine zusätzliche Buchung; wie viele pro Woche erlaubt sind, legt die Verwaltung fest.'],
            ['**Freigeben**', 'Brauchst du dein Zeitfenster nicht? Gib es frei, dann können andere es buchen. Solange es niemand bucht, kannst du es zurückholen.'],
            ['**Ändern**', 'Eine Notiz dazuschreiben («60° Wäsche») oder nur einen Teil der Zeit nutzen, damit andere sehen, wann es frei ist.'],
            ['**Verschieben**', 'Zieh dein Zeitfenster auf ein freies. Oder tippe darauf, dann auf «Verschieben» und auf ein freies Zeitfenster.'],
            ['**Einchecken**', 'Tippe auf «Einchecken», wenn du in der Waschküche bist. Dann kann niemand dein Zeitfenster übernehmen.'],
            ['**Fertig – Rest freigeben**', 'Früher fertig? Ab sofort kann jede Wohnung den Rest buchen, ohne dass es als zusätzliche Buchung zählt. «Doch noch nicht fertig» nimmt es zurück, solange niemand gebucht hat.'],
            ['**Übernehmen**', 'Ein fremdes Zeitfenster übernehmen, das nicht genutzt wird: je nach Hausregel nach einer Wartezeit, jederzeit oder nie. Die andere Wohnung wird benachrichtigt.'],
          ],
        },
      },
      { h2: 'Meine Wäsche' },
      { p: 'Unter «Meine Wäsche» siehst du, was als Nächstes kommt, die festen Zeiten deiner Wohnung («Jeden zweiten Dienstag, 07:00–17:00») und deine Benachrichtigungen. Dort stellst du auch die Schriftgrösse ein (Normal, Gross, Sehr gross) und abonnierst den Kalender.' },
      { callout: 'Kalender-Abo und E-Mail-Benachrichtigungen gibt es im gehosteten Waschplaner mit [Plus](/pricing) und auf selbst betriebenen Servern.' },
      { h2: 'Aufs Handy legen' },
      {
        list: [
          '**iPhone und iPad:** In Safari auf «Teilen» und dann auf «Zum Home-Bildschirm» tippen.',
          '**Android:** Im Chrome-Menü «App installieren» oder «Zum Startbildschirm hinzufügen» wählen.',
          'Danach öffnen sich der Plan und «Meine Wäsche» auch ohne Internet, zum Ansehen.',
        ],
      },
    ],
  },
  {
    slug: 'admin',
    section: 'use',
    icon: 'sliders',
    title: 'Für die Verwaltung',
    summary: 'Fester Plan, Maschinen, Regeln, Wohnungen und Personen.',
    blocks: [
      { p: 'Unter «Verwalten» änderst du alles, was du im Assistenten eingerichtet hast. Änderungen sammeln sich in einer Leiste am unteren Rand, die sagt, was sich ändert («2 Zeitfenster geändert · 1 neu»). Sie gelten erst nach «Speichern». Was sich nicht rückgängig machen lässt, fragt vorher nach und nennt die Folgen.' },
      { h2: 'Die Bereiche' },
      {
        table: {
          head: ['Bereich', 'Was du dort machst'],
          rows: [
            ['**Fester Plan**', 'Wer welches Zeitfenster regelmässig hat. Derselbe Editor wie im Assistenten, mit Monatskalender und «Zeit pro Wohnung». Zeitfenster lassen sich ziehen oder «malen»: Wohnung wählen, Zeitfenster antippen.'],
            ['**Maschinen & Zeiten**', 'Maschinen und Räume, ihre Zeitfenster pro Tag und wie gebucht wird. Eine Waschküche lässt sich in einzelne Maschinen aufteilen und wieder zusammenlegen; Zeiten, feste Zeiten und Buchungen bleiben erhalten.'],
            ['**Regeln**', 'Zusätzliche Buchungen pro Woche (gezählt in Zeitfenstern oder Tagen), wie weit im Voraus gebucht werden darf und wann andere ein Zeitfenster übernehmen dürfen.'],
            ['**Einladen**', 'Aushang drucken und den Einladungslink teilen oder erneuern.'],
            ['**Wohnungen**', 'Bezeichnungen, Farben und Zugangscodes. Ein neuer Code macht die alte Karte ungültig; wer schon angemeldet ist, bleibt angemeldet.'],
            ['**Personen**', 'Wer zu welcher Wohnung gehört. Personen entfernen.'],
            ['**Haus**', 'Name und allgemeine Einstellungen des Hauses.'],
            ['**Aktivitäten**', 'Wer wann was gebucht, freigegeben oder geändert hat.'],
          ],
        },
      },
      { h2: 'Regeln fürs Übernehmen' },
      {
        list: [
          '**Nach der Wartezeit** (Standard): erst wenn das Zeitfenster begonnen hat und die Wartezeit vorbei ist, und nur, wenn niemand eingecheckt hat.',
          '**Jederzeit**, solange niemand eingecheckt hat.',
          '**Nie:** Zeitfenster anderer lassen sich nicht übernehmen.',
        ],
      },
      { p: 'Die betroffene Wohnung bekommt eine Benachrichtigung in der App, mit Plus oder eigenem Mailserver auch per E-Mail.' },
      { h2: 'Wenn sich feste Zeiten überschneiden' },
      { p: 'Gelten für ein Zeitfenster zwei feste Zeiten, gewinnt die, die sich seltener wiederholt. So geht «Jeden Montag Wohnung A, aber am ersten Montag im Monat Wohnung B».' },
      { h2: 'Live-Bildschirm' },
      { p: 'Für einen Bildschirm in der Waschküche gibt es eine Ansicht ohne Anmeldung, die sich jede Minute selbst aktualisiert. Im gehosteten Waschplaner ist sie Teil von [Plus](/pricing).' },
    ],
  },
  {
    slug: 'self-hosting',
    section: 'run',
    icon: 'server',
    title: 'Selbst hosten',
    summary: 'Waschplaner mit Docker auf deinem eigenen Server betreiben.',
    blocks: [
      { p: 'Waschplaner besteht aus drei Containern: der Datenbank (PostgreSQL 17), dem Server (Go) und der Weboberfläche (nginx). Docker Compose startet alles zusammen. Selbst betrieben hast du alle Funktionen, ohne Kosten und ohne Grenzen.' },
      { h2: 'Was du brauchst' },
      {
        list: [
          'Einen Linux-Server, Mini-PC oder eine NAS mit **Docker** und **Docker Compose**.',
          'Eine **Adresse** (Domain oder Subdomain), damit Bewohner:innen den Plan über HTTPS erreichen.',
          'Optional einen **Mailserver** (SMTP) für E-Mail-Benachrichtigungen und «Passwort vergessen».',
        ],
      },
      { h2: 'Schnellstart' },
      { p: 'Zum Ausprobieren auf deinem Computer:' },
      { code: 'git clone {repo}.git waschplaner\ncd waschplaner\ndocker compose up -d --build' },
      { p: 'Öffne danach [http://localhost:8080](http://localhost:8080) und tippe auf «Jetzt einrichten». Die Datenbank wird beim Start automatisch eingerichtet und aktualisiert.' },
      { h2: 'Für den Betrieb' },
      {
        steps: [
          { title: 'Einstellungen anlegen', text: 'Kopiere die Vorlage und erzeuge ein sicheres Datenbank-Passwort:', code: 'cp .env.example .env\nopenssl rand -base64 32' },
          { title: 'Wichtige Werte setzen', text: '`POSTGRES_PASSWORD` auf das erzeugte Passwort, `PUBLIC_URL` auf deine Adresse (z. B. `https://waschplaner.example.ch`) und `COOKIE_SECURE=true`, sobald HTTPS läuft. Alle Werte stehen unter [Konfiguration](/docs/configuration).' },
          { title: 'Starten', code: 'docker compose up -d --build' },
        ],
      },
      { h2: 'HTTPS mit Caddy' },
      { p: 'Die Weboberfläche lauscht auf Port 8080, ohne Verschlüsselung. Ein Reverse Proxy davor kümmert sich um HTTPS. Mit [Caddy](https://caddyserver.com) genügt diese Datei; das Zertifikat holt Caddy selbst:' },
      { code: 'waschplaner.example.ch {\n\treverse_proxy localhost:8080\n}', title: 'Caddyfile' },
      { callout: 'Setze `HTTP_PORT=127.0.0.1:8080`, damit Port 8080 nur für Caddy erreichbar ist. Und vergiss `COOKIE_SECURE=true` und `PUBLIC_URL=https://…` nicht: Die Adresse steht in E-Mails, Kalender- und Einladungslinks.', tone: 'warn' },
      { h2: 'Nur euer Haus' },
      { p: 'Nachdem du euer Haus erstellt hast, setze `ALLOW_SIGNUP=false` und starte neu. Dann kann niemand sonst auf deinem Server ein Haus anlegen.' },
      { h2: 'E-Mail' },
      { p: 'Ohne Mailserver gibt es nur Benachrichtigungen in der App, und «Passwort vergessen» funktioniert nicht. Trage die Zugangsdaten deines Mailanbieters ein:' },
      { code: 'SMTP_HOST=smtp.example.ch\nSMTP_PORT=587\nSMTP_USER=waschplaner@example.ch\nSMTP_PASSWORD=…\nSMTP_FROM=Waschplaner <waschplaner@example.ch>', title: '.env' },
      { h2: 'Schutz vor Spam' },
      { p: 'Optional schützt Google reCAPTCHA die öffentlichen Formulare: Anmelden, Haus einrichten, Beitreten und Passwort vergessen. Es ist aus, solange nicht beide Schlüssel gesetzt sind.' },
      { callout: 'Mit reCAPTCHA lädt der Browser auf diesen Seiten ein Skript von Google. Erwähne das in deiner Datenschutzerklärung.', tone: 'privacy' },
      { h2: 'Backups' },
      { p: 'Alle Daten liegen in der Datenbank. So sicherst du sie in eine Datei:' },
      { code: 'docker compose exec -T db sh -c \'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"\' | gzip > waschplaner-$(date +%F).sql.gz' },
      { p: 'Und so stellst du sie in einer leeren Datenbank wieder her:' },
      { code: 'gunzip -c waschplaner-2026-09-23.sql.gz | docker compose exec -T db sh -c \'psql -U "$POSTGRES_USER" "$POSTGRES_DB"\'' },
      { callout: 'Richte dafür einen täglichen Cronjob ein und bewahre einige Sicherungen an einem anderen Ort auf.', tone: 'tip' },
      { h2: 'Aktualisieren' },
      { code: 'git pull\ndocker compose up -d --build' },
      { p: 'Änderungen an der Datenbank laufen beim Start des Servers automatisch. Mach vorher ein Backup.' },
      { h2: 'Mitentwickeln' },
      { p: 'Wie du Waschplaner ohne Docker startest, die Tests laufen lässt und wo was im Code liegt, steht im [README]({repo}#readme).' },
    ],
  },
  {
    slug: 'configuration',
    section: 'run',
    icon: 'terminal',
    title: 'Konfiguration',
    summary: 'Alle Einstellungen für einen eigenen Server.',
    blocks: [
      { p: 'Docker Compose liest die Datei `.env` im Projektordner. Nach einer Änderung übernimmt `docker compose up -d` die neuen Werte.' },
      { h2: 'Grundlagen' },
      {
        table: {
          head: ['Variable', 'Standard', 'Bedeutung'],
          rows: [
            ['`POSTGRES_PASSWORD`', '`waschplan`', 'Passwort der Datenbank. **Für den Betrieb unbedingt ändern.**'],
            ['`POSTGRES_USER`', '`waschplan`', 'Benutzername der Datenbank.'],
            ['`POSTGRES_DB`', '`waschplan`', 'Name der Datenbank.'],
            ['`HTTP_PORT`', '`8080`', 'Port auf dem Server. `127.0.0.1:8080` macht ihn nur lokal erreichbar, z. B. hinter einem Reverse Proxy.'],
            ['`PUBLIC_URL`', '`http://localhost:8080`', 'Die Adresse, unter der Bewohner:innen Waschplaner öffnen. Steht in E-Mails, Kalender- und Einladungslinks und schützt die Formulare (CSRF).'],
            ['`COOKIE_SECURE`', '`false`', '`true`, sobald Waschplaner über HTTPS läuft.'],
            ['`ALLOW_SIGNUP`', '`true`', '`false`, damit niemand weitere Häuser anlegen kann.'],
          ],
        },
      },
      { h2: 'E-Mail' },
      {
        table: {
          head: ['Variable', 'Standard', 'Bedeutung'],
          rows: [
            ['`SMTP_HOST`', '–', 'Der Mailserver. Leer: nur Benachrichtigungen in der App.'],
            ['`SMTP_PORT`', '`587`', 'Port des Mailservers.'],
            ['`SMTP_USER`', '–', 'Benutzername beim Mailserver.'],
            ['`SMTP_PASSWORD`', '–', 'Passwort beim Mailserver.'],
            ['`SMTP_FROM`', '`Waschplaner <noreply@example.com>`', 'Absender der E-Mails.'],
          ],
        },
      },
      { h2: 'reCAPTCHA' },
      {
        table: {
          head: ['Variable', 'Standard', 'Bedeutung'],
          rows: [
            ['`RECAPTCHA_SITE_KEY`', '–', 'Öffentlicher Schlüssel von Google. reCAPTCHA ist nur an, wenn beide Schlüssel gesetzt sind.'],
            ['`RECAPTCHA_SECRET`', '–', 'Geheimer Schlüssel von Google.'],
            ['`RECAPTCHA_VERSION`', '`v2`', '`v2`: das Häkchen «Ich bin kein Roboter». `v3`: unsichtbar, mit einer Bewertung.'],
            ['`RECAPTCHA_MIN_SCORE`', '`0.5`', 'Nur bei `v3`: die kleinste akzeptierte Bewertung, von 0 bis 1.'],
          ],
        },
      },
      { h2: 'Für Fortgeschrittene' },
      { p: 'Diese Werte stehen nicht in der `.env`. Um sie zu ändern, passe sie in `docker-compose.yml` unter `api` → `environment` an oder ergänze sie dort.' },
      {
        table: {
          head: ['Variable', 'Standard', 'Bedeutung'],
          rows: [
            ['`DATABASE_URL`', 'aus `POSTGRES_*`', 'Verbindung zur Datenbank.'],
            ['`LISTEN_ADDR`', '`:8080`', 'Adresse, auf der der Server im Container lauscht.'],
            ['`TRUST_PROXY`', '`true`', 'Die Adresse der Besucher:innen aus `X-Forwarded-For` übernehmen. Wichtig für die Begrenzung von Anmeldeversuchen.'],
            ['`AUTH_RATE_LIMIT`', '`10`', 'Wie viele Anmeldungen, Registrierungen und Beitritte eine Adresse pro Minute versuchen darf.'],
          ],
        },
      },
    ],
  },
  {
    slug: 'glossary',
    section: 'more',
    icon: 'book',
    title: 'Begriffe',
    summary: 'Die Wörter, die Waschplaner verwendet, auf Deutsch und Englisch.',
    blocks: [
      { p: 'Waschplaner verwendet überall dieselben Wörter. Hier stehen sie auf Deutsch und Englisch.' },
      {
        table: {
          head: ['Deutsch', 'English', 'Bedeutung'],
          rows: [
            ['Plan', 'Schedule', 'Die Wochenansicht, die alle sehen.'],
            ['Fester Plan, feste Zeit', 'Regular schedule, regular time', 'Wer welches Zeitfenster immer wieder hat, wie ein wiederkehrender Termin.'],
            ['Zeitfenster', 'Time slot', 'Die Zeit, die eine Wohnung auf einmal bucht, z. B. 07:00–12:00.'],
            ['Buchen', 'Book', 'Ein freies Zeitfenster nehmen.'],
            ['Zusätzlich', 'Extra', 'Eine Buchung ausserhalb der eigenen festen Zeiten; pro Woche begrenzt.'],
            ['Freigeben', 'Free up', 'Ein Zeitfenster zurückgeben, damit andere es buchen können.'],
            ['Übernehmen', 'Take over', 'Ein nicht genutztes Zeitfenster einer anderen Wohnung nehmen; sie wird benachrichtigt.'],
            ['Fertig – Rest freigeben', 'Done – free the rest', 'Früher fertig: Der Rest des laufenden Zeitfensters ist für alle frei.'],
            ['Rest buchen', 'Book the rest', 'Den Rest eines Zeitfensters buchen, das eine andere Wohnung früher beendet hat. Zählt nie als zusätzliche Buchung.'],
            ['Einchecken', 'Check in', '«Ich bin jetzt in der Waschküche.» Schützt das Zeitfenster.'],
            ['Meine Wäsche', 'My laundry', 'Die eigene Seite: nächste Zeitfenster, feste Zeiten, Benachrichtigungen.'],
            ['Haus', 'House', 'Ein Gebäude mit eigenem Plan und eigenen Regeln.'],
            ['Wohnung', 'Flat', 'Ein Haushalt. Buchungen gehören Wohnungen.'],
            ['Bewohner:in', 'Resident', 'Wer mit dem Zugangscode einer Wohnung beigetreten ist.'],
            ['Verwaltung', 'Administrator', 'Wer den Plan einrichtet und verwaltet.'],
            ['Waschküche', 'Laundry room', 'Mehrere Maschinen, die zusammen gebucht werden.'],
            ['Maschine', 'Machine', 'Waschmaschine, Tumbler oder Trockenraum.'],
            ['Zugangscode', 'Access code', 'Die 6 Ziffern auf der Karte einer Wohnung, zum Beitreten.'],
            ['Aushang', 'Poster', 'Die gedruckte Seite mit dem QR-Code des Hauses.'],
          ],
        },
      },
    ],
  },
]
