// Help pages in English (British spelling). Same slugs and blocks as docs.de.js.
export default [
  {
    slug: 'setup',
    section: 'use',
    icon: 'wand',
    title: 'Setting up a house',
    summary: 'The six-step wizard, and what comes next.',
    blocks: [
      { p: 'The wizard asks for everything the schedule needs in six short steps. Your entries stay on this device (without the password) until the last step creates the house. You can change everything later.' },
      { callout: 'Hosted: open [{app}/setup]({app}/setup). Self-hosted: open your server’s address and tap “Set one up – it takes 5 minutes”.', tone: 'tip' },
      { h2: 'The six steps' },
      {
        steps: [
          { title: 'House', text: 'The name of the house and the flats. “Quick fill” creates labels like “Ground left, Ground right, 1st left”. Tap a dot to change a flat’s colour.' },
          { title: 'Laundry room', text: 'How many washing machines, tumble dryers and drying rooms there are, and how people book them: **all together** (one laundry room per booking), **each separately**, or **mixed** – for example washer and dryer together, the drying room separately.' },
          { title: 'Times', text: 'The days for laundry and how each day is split into time slots: the whole day, 2 or 3 time slots, every 2 hours or your own times, optionally different on some days. A week view shows the result.' },
          { title: 'Regular schedule', text: 'Who has which time slot, like repeating calendar events: every week, every 2–4 weeks or once a month (1st–4th or last weekday). The wizard suggests a fair split; a month calendar and “Time per flat” show the result.' },
          { title: 'Rules', text: 'How many extra bookings are allowed, how far ahead, and what happens to unused time slots. A plain-language summary shows what applies.' },
          { title: 'Login', text: 'The administrator’s first name, e-mail and password. You also choose **Free** (to print) or **Plus** ({trial} days on us, no payment details) and see a summary of everything.' },
        ],
      },
      { callout: 'Use labels like “2nd floor left” instead of family names. The schedule hangs in the laundry room, and with Plus everyone in the house sees it online.', tone: 'privacy' },
      { h2: 'Next: print or invite' },
      {
        list: [
          '**Free:** print the schedule under “Manage → Print”: two weeks per A4 page, for each machine or room, up to {printFree} weeks at a time (a whole year with Plus). The print dialog can also save it as a PDF. If you change something later, simply print again.',
          '**Plus:** the “Invite” page explains the next steps: print the poster with the QR code and put it up in the laundry room, and give each flat its 6-digit access code. The cards with their own QR code fill it in automatically.',
          '**Self-hosted, and only one house?** Then set `ALLOW_SIGNUP=false` so nobody else can create houses.',
        ],
      },
    ],
  },
  {
    slug: 'residents',
    section: 'use',
    icon: 'users',
    title: 'For residents',
    summary: 'Join, book, free up: the schedule day to day.',
    blocks: [
      { callout: 'You use the schedule online when your house has [Plus](/pricing). Otherwise it hangs on paper in the laundry room, and the app says “The online schedule is paused”.' },
      { h2: 'Joining' },
      {
        steps: [
          { title: 'Scan the QR code', text: 'The one on the poster in the laundry room or on your flat’s card.' },
          { title: 'Pick your flat', text: 'And enter the 6-digit access code. With your flat’s card it is already filled in.' },
          { title: 'Done', text: 'You stay logged in on this device. With an e-mail and password you can also log in on other devices – if you want to.' },
        ],
      },
      { h2: 'The schedule' },
      { p: 'Each colour is a flat. Your flat’s time slots have a thick border and a person icon. On wide screens you see the whole week; on phones one day at a time. Tap the week title to jump to any day.' },
      { h2: 'What you can do' },
      {
        table: {
          head: ['Action', 'How'],
          rows: [
            ['**Book**', 'Tap a free time slot and confirm. Outside your regular times this is an extra booking; the administrator decides how many are allowed per week.'],
            ['**Free up**', 'Don’t need your time slot? Free it up so others can book it. As long as nobody books it, you can take it back.'],
            ['**Edit**', 'Add a note (“60° wash”) or use only part of the time, so others can see when it is free.'],
            ['**Move**', 'Drag your time slot onto a free one. Or tap it, then “Move”, then a free time slot.'],
            ['**Check in**', 'Tap “Check in” when you are in the laundry room. Then nobody can take over your time slot.'],
            ['**Done – free the rest**', 'Finished early? From now on any flat can book the rest, and it never counts as an extra booking. “Not done yet” takes it back as long as nobody has booked it.'],
            ['**Take over**', 'Take another flat’s unused time slot: depending on the house rules after a grace period, at any time, or never. The other flat is notified.'],
          ],
        },
      },
      { h2: 'My laundry' },
      { p: 'Under “My laundry” you see what comes next, your flat’s regular times (“Every other Tuesday, 07:00–17:00”) and your notifications. This is where you choose whether changes to your time slots also come by e-mail, subscribe to the calendar and set the text size (Normal, Large, Extra large).' },
      { callout: 'Anyone with the calendar subscription’s address sees your flat’s times. Share it only with your household.', tone: 'privacy' },
      { h2: 'As an app on your phone' },
      {
        list: [
          '**Android and computers:** under “My laundry → As an app”, tap “Install as an app”.',
          '**iPhone and iPad:** in Safari, tap “Share” and then “Add to Home Screen”.',
          'After that, the schedule also opens without internet and shows what was last loaded. Booking works again as soon as you are online.',
        ],
      },
      { h2: 'When Plus has ended' },
      { p: 'Then you can still look at the schedule for {view} days, but not book or change anything. After that it hangs on paper in the laundry room again – until the administrator buys Plus again.' },
    ],
  },
  {
    slug: 'admin',
    section: 'use',
    icon: 'sliders',
    title: 'For administrators',
    summary: 'Regular schedule, printing, machines, rules, flats and Plus.',
    blocks: [
      { p: 'Under “Manage” you change everything you set up in the wizard. Changes collect in a bar at the bottom that says what will change (“2 time slots changed · 1 new”). They apply only after “Save”. Anything that cannot be undone asks first and names the consequences.' },
      { h2: 'The sections' },
      {
        table: {
          head: ['Section', 'What you do there'],
          rows: [
            ['**Regular schedule**', 'Who has which time slot. The same editor as in the wizard, with a month calendar and “Time per flat”. Drag time slots (to move or swap them), or “paint”: pick a flat, then tap or swipe over time slots.'],
            ['**Machines & times**', 'Machines and rooms, their time slots per day and how people book them. A laundry room can be split into its machines and combined again; times, regular times and bookings are kept.'],
            ['**Rules** · Plus', 'Extra bookings per week (counted in time slots or days), how far ahead people can book, and when others may take over a time slot.'],
            ['**Print**', 'Two weeks per A4 page, from a week of your choice, for the machines and rooms you pick: up to {printFree} weeks at a time on Free, a whole year with Plus. The print dialog can also “Save as PDF”.'],
            ['**Invite** · Plus', 'Print the poster with the QR code and share or renew the invitation link.'],
            ['**Flats**', 'Labels, colours and access codes. A new code makes the old card stop working; anyone already logged in stays logged in.'],
            ['**People** · Plus', 'Who belongs to which flat. Remove people.'],
            ['**Activity** · Plus', 'Who booked, freed up or changed what, and when.'],
            ['**Settings**', 'The house’s name, time zone and language, whether people can join with the QR code, and whether there is a public schedule view.'],
            ['**Plus**', 'Try, buy or renew Plus, and see past payments.'],
          ],
        },
      },
      { p: 'On Free, the sections that belong to Plus are shown, but inactive and marked as Plus.' },
      { h2: 'Managing Plus' },
      {
        list: [
          '**Try it:** every house can use Plus for free for {trial} days, once, without payment details – in the last step of the setup or with the offer under “Manage”. You get an e-mail {trialRemind} days before it ends.',
          '**Buy it:** under “Manage → Plus”, for a year, on Stripe’s secure payment page. You pay per active flat. If you buy during the trial, the year only starts when it ends.',
          '**Renew it:** in the last {renew} days; the new year starts when the old one ends. We remind you by e-mail {remind} days before the end. Nothing renews by itself.',
          '**A new flat during the year:** the “Flats” page asks and opens the payment page for its share until the end of the year (at least CHF {min}). The flat starts once it is paid; nobody else notices anything.',
          '**When Plus ends:** residents can still look at the schedule for {view} days. After that the house is on Free: you keep changing and printing the schedule, and everything stays saved.',
        ],
      },
      { h2: 'Rules for taking over' },
      {
        list: [
          '**After the grace period** (default): only once the time slot has started and the grace period is over, and only if nobody checked in.',
          '**At any time**, as long as nobody checked in.',
          '**Never:** other flats’ time slots cannot be taken over.',
        ],
      },
      { p: 'The flat concerned gets an in-app notification, and also an e-mail if it has turned e-mails on.' },
      { h2: 'When regular times overlap' },
      { p: 'If two regular times apply to one time slot, the one that repeats less often wins. That is how “every Monday flat A, but the first Monday of the month flat B” works.' },
      { h2: 'Public schedule view' },
      { p: 'For a screen in the laundry room there is a view without login, without notes and without people’s names. It refreshes itself every minute. You switch it on under “Settings”; it is part of Plus.' },
    ],
  },
  {
    slug: 'self-hosting',
    section: 'run',
    icon: 'server',
    title: 'Self-hosting',
    summary: 'Run Waschplaner on your own server with Docker.',
    blocks: [
      { p: 'Waschplaner consists of three containers: the database (PostgreSQL 17), the server (Go) and the web interface (nginx). Docker Compose starts them together. Self-hosted, you get every feature, and Plus costs nothing unless you set up payments.' },
      { h2: 'What you need' },
      {
        list: [
          'A Linux server, mini PC or NAS with **Docker** and **Docker Compose**.',
          'An **address** (domain or subdomain) so residents can reach the schedule over HTTPS.',
          'Optionally a **mail server** (SMTP) for e-mail notifications and password resets.',
        ],
      },
      { h2: 'Quick start' },
      { p: 'To try it out on your computer:' },
      { code: 'git clone {repo}.git waschplaner\ncd waschplaner\ndocker compose up -d --build' },
      { p: 'Then open [http://localhost:8080](http://localhost:8080) and tap “Set one up – it takes 5 minutes”. The database is set up and updated automatically on start.' },
      { h2: 'For production' },
      {
        steps: [
          { title: 'Create the settings', text: 'Copy the template and generate a strong database password:', code: 'cp .env.example .env\nopenssl rand -base64 32' },
          { title: 'Set the important values', text: '`POSTGRES_PASSWORD` to the generated password, `PUBLIC_URL` to your address (e.g. `https://laundry.example.org`), `COOKIE_SECURE=true` once HTTPS works, and `FAKE_STRIPE=false` for Plus without payments. Every value is listed under [Configuration](/docs/configuration).' },
          { title: 'Start', code: 'docker compose up -d --build' },
        ],
      },
      { h2: 'Plus and payments' },
      { p: '`docker-compose.yml` sets `FAKE_STRIPE=true`. Plus is then “paid” on a simulated payment page, in test mode and without real money, so you can try everything. For production, pick one of two ways:' },
      {
        list: [
          '**Without payments**, e.g. just for your own house: `FAKE_STRIPE=false` and leave `STRIPE_SECRET_KEY` empty. Then you simply switch Plus on under “Manage → Plus”, for free.',
          '**With payments through Stripe:** put your key in `STRIPE_SECRET_KEY`. Test first with a test key (`sk_test_…`) and the test card 4242 4242 4242 4242; test payments stop counting once a live key is set. A key always takes precedence over `FAKE_STRIPE`.',
        ],
      },
      { code: 'FAKE_STRIPE=false\nSTRIPE_SECRET_KEY=sk_test_…\nSTRIPE_WEBHOOK_SECRET=whsec_…\nSTRIPE_PAYMENT_METHODS=card,twint\nPLUS_PRICE=2\nPLUS_CURRENCY=CHF', title: '.env' },
      { p: 'Recommended: in the Stripe dashboard under “Developers → Webhooks”, add a webhook for `https://<your address>/api/stripe/webhook` with the events `checkout.session.completed` and `checkout.session.async_payment_succeeded`, and put its signing secret in `STRIPE_WEBHOOK_SECRET`. Then payments count even if someone closes the payment page before coming back.' },
      { callout: 'Waschplaner sends no receipts. Turn on the e-mails for successful payments in the Stripe dashboard. TWINT needs the currency CHF and must be turned on in the dashboard.', tone: 'tip' },
      { h2: 'HTTPS with Caddy' },
      { p: 'The web interface listens on port 8080 without encryption. A reverse proxy in front takes care of HTTPS. With [Caddy](https://caddyserver.com) this file is all you need; Caddy fetches the certificate itself:' },
      { code: 'laundry.example.org {\n\treverse_proxy localhost:8080\n}', title: 'Caddyfile' },
      { callout: 'Set `HTTP_PORT=127.0.0.1:8080` so that only Caddy can reach port 8080. And do not forget `COOKIE_SECURE=true` and `PUBLIC_URL=https://…`: the address appears in e-mails, calendar and invitation links, and the payment page returns to it.', tone: 'warn' },
      { h2: 'Only your house' },
      { p: 'Once you have created your house, set `ALLOW_SIGNUP=false` and restart. Then nobody else can create a house on your server.' },
      { h2: 'E-mail' },
      { p: 'Without a mail server there are only in-app notifications, and nobody can reset a forgotten password. E-mails to residents are part of Plus. Enter your mail provider’s details:' },
      { code: 'SMTP_HOST=smtp.example.org\nSMTP_PORT=587\nSMTP_USER=laundry@example.org\nSMTP_PASSWORD=…\nSMTP_FROM=Waschplaner <laundry@example.org>', title: '.env' },
      { h2: 'Spam protection' },
      { p: 'Optionally, Google reCAPTCHA protects the public forms for logging in, setting up a house, joining and resetting a password. It is off unless both keys are set.' },
      { callout: 'With reCAPTCHA, the browser loads a script from Google on these pages. Mention this in your privacy policy.', tone: 'privacy' },
      { h2: 'Backups' },
      { p: 'All data lives in the database. This saves it to a file:' },
      { code: 'docker compose exec -T db sh -c \'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"\' | gzip > waschplaner-$(date +%F).sql.gz' },
      { p: 'And this restores it into an empty database:' },
      { code: 'gunzip -c waschplaner-2026-09-23.sql.gz | docker compose exec -T db sh -c \'psql -U "$POSTGRES_USER" "$POSTGRES_DB"\'' },
      { callout: 'Set up a daily cron job for this and keep a few backups somewhere else.', tone: 'tip' },
      { h2: 'Updating' },
      { code: 'git pull\ndocker compose up -d --build' },
      { p: 'Database changes run automatically when the server starts. Make a backup first.' },
      { h2: 'Contributing' },
      { p: 'How to run Waschplaner without Docker, run the tests and find your way around the code is in the [README]({repo}#readme).' },
    ],
  },
  {
    slug: 'configuration',
    section: 'run',
    icon: 'terminal',
    title: 'Configuration',
    summary: 'Every setting for your own server.',
    blocks: [
      { p: 'Docker Compose reads the `.env` file in the project folder. After a change, `docker compose up -d` applies the new values. “Default” is the value in `docker-compose.yml`.' },
      { h2: 'Basics' },
      {
        table: {
          head: ['Variable', 'Default', 'Meaning'],
          rows: [
            ['`POSTGRES_PASSWORD`', '`waschplan`', 'The database password. **Always change it for production.**'],
            ['`POSTGRES_USER`', '`waschplan`', 'The database user name.'],
            ['`POSTGRES_DB`', '`waschplan`', 'The database name.'],
            ['`HTTP_PORT`', '`8080`', 'The port on the server. `127.0.0.1:8080` makes it reachable only locally, e.g. behind a reverse proxy.'],
            ['`PUBLIC_URL`', '`http://localhost:8080`', 'The address residents open Waschplaner at. It appears in e-mails, calendar and invitation links, and protects the forms (CSRF).'],
            ['`COOKIE_SECURE`', '`false`', '`true` once Waschplaner runs over HTTPS.'],
            ['`ALLOW_SIGNUP`', '`true`', '`false` so nobody can create further houses.'],
          ],
        },
      },
      { h2: 'Plus and payments' },
      {
        table: {
          head: ['Variable', 'Default', 'Meaning'],
          rows: [
            ['`PLUS_PRICE`', '`2`', 'The price per flat and year, e.g. `1` or `4.50`.'],
            ['`PLUS_CURRENCY`', '`CHF`', 'The currency as a code, e.g. `CHF` or `EUR`. Only currencies with two decimal places.'],
            ['`FAKE_STRIPE`', '`true`', 'A simulated payment page in test mode; nothing is charged. `false` and no key: Plus is a switch that costs nothing.'],
            ['`STRIPE_SECRET_KEY`', '–', 'Stripe key: `sk_test_…` for test mode, `sk_live_…` for real payments. Takes precedence over `FAKE_STRIPE`.'],
            ['`STRIPE_WEBHOOK_SECRET`', '–', 'The webhook’s signing secret. Confirms payments even if nobody comes back from the payment page.'],
            ['`STRIPE_PAYMENT_METHODS`', '–', 'Payment methods, e.g. `card,twint`. Empty: whatever is turned on in the Stripe dashboard.'],
          ],
        },
      },
      { h2: 'E-mail' },
      {
        table: {
          head: ['Variable', 'Default', 'Meaning'],
          rows: [
            ['`SMTP_HOST`', '–', 'The mail server. Empty: in-app notifications only.'],
            ['`SMTP_PORT`', '`587`', 'The mail server’s port.'],
            ['`SMTP_USER`', '–', 'User name at the mail server.'],
            ['`SMTP_PASSWORD`', '–', 'Password at the mail server.'],
            ['`SMTP_FROM`', '`Waschplaner <noreply@example.com>`', 'The sender of the e-mails.'],
          ],
        },
      },
      { h2: 'reCAPTCHA' },
      {
        table: {
          head: ['Variable', 'Default', 'Meaning'],
          rows: [
            ['`RECAPTCHA_SITE_KEY`', '–', 'Google’s public key. reCAPTCHA is on only if both keys are set.'],
            ['`RECAPTCHA_SECRET`', '–', 'Google’s secret key.'],
            ['`RECAPTCHA_VERSION`', '`v2`', '`v2`: the “I’m not a robot” checkbox. `v3`: invisible, with a score.'],
            ['`RECAPTCHA_MIN_SCORE`', '`0.5`', '`v3` only: the lowest accepted score, from 0 to 1.'],
          ],
        },
      },
      { h2: 'Advanced' },
      { p: 'These values are not in `.env`. To change them, edit or add them in `docker-compose.yml` under `api` → `environment`.' },
      {
        table: {
          head: ['Variable', 'Default', 'Meaning'],
          rows: [
            ['`DATABASE_URL`', 'from `POSTGRES_*`', 'The connection to the database.'],
            ['`LISTEN_ADDR`', '`:8080`', 'The address the server listens on inside the container.'],
            ['`TRUST_PROXY`', '`true`', 'Take visitors’ addresses from `X-Forwarded-For`. This matters for limiting login attempts.'],
            ['`AUTH_RATE_LIMIT`', '`10`', 'How many logins, sign-ups and joins one address may try per minute.'],
            ['`MAIL_LOG`', '`false`', '`true`: write e-mails to the log instead of sending them, for development.'],
          ],
        },
      },
    ],
  },
  {
    slug: 'glossary',
    section: 'more',
    icon: 'book',
    title: 'Glossary',
    summary: 'The words Waschplaner uses, in German and English.',
    blocks: [
      { p: 'Waschplaner uses the same words everywhere. Here they are in German and English, the app’s languages.' },
      {
        table: {
          head: ['Deutsch', 'English', 'Meaning'],
          rows: [
            ['Plan', 'Schedule', 'The week view everyone sees.'],
            ['Fester Plan, feste Zeit', 'Regular schedule, regular time', 'Who has which time slot again and again, like a repeating calendar event.'],
            ['Zeitfenster', 'Time slot', 'The time one flat books in one go, e.g. 07:00–12:00.'],
            ['Buchen', 'Book', 'Taking a free time slot.'],
            ['Zusätzlich', 'Extra', 'A booking outside the flat’s own regular times; limited per week.'],
            ['Freigeben', 'Free up', 'Giving back a time slot so others can book it.'],
            ['Übernehmen', 'Take over', 'Taking another flat’s unused time slot; that flat is notified.'],
            ['Fertig – Rest freigeben', 'Done – free the rest', 'Finishing early: the rest of the running time slot is free for anyone.'],
            ['Rest buchen', 'Book the rest', 'Booking what is left of a time slot another flat finished early. Never an extra booking.'],
            ['Einchecken', 'Check in', '“I am in the laundry room now.” Protects the time slot.'],
            ['Meine Wäsche', 'My laundry', 'Your own page: next time slots, regular times, notifications.'],
            ['Haus', 'House', 'One building with its own schedule and rules.'],
            ['Wohnung', 'Flat', 'A household. Bookings belong to flats.'],
            ['Bewohner:in', 'Resident', 'Someone who joined with a flat’s access code.'],
            ['Verwaltung', 'Administrator', 'Whoever sets up and manages the schedule.'],
            ['Waschküche', 'Laundry room', 'Several machines booked together.'],
            ['Maschine', 'Machine', 'Washing machine, tumble dryer or drying room.'],
            ['Zugangscode', 'Access code', 'The 6 digits on a flat’s card, used to join.'],
            ['Aushang', 'Poster', 'The printed page with the house’s QR code.'],
            ['Gratis', 'Free', 'The schedule without Plus: the administrator creates it and prints it, up to {printFree} weeks at a time.'],
            ['Plus', 'Plus', 'Everyone uses the schedule online, with e-mails, calendar subscriptions and the public schedule view.'],
            ['Öffentliche Plan-Ansicht', 'Public schedule view', 'The schedule without logging in, for a screen in the laundry room.'],
            ['Kaufen, verlängern', 'Buy, renew', 'Paying for a year of Plus; renewing adds a year.'],
            ['Bezahlseite', 'Payment page', 'Stripe’s page where the administrator pays.'],
          ],
        },
      },
    ],
  },
]
