// Help pages in French. Same slugs and blocks as docs.de.js. The app is in German
// and English, so buttons are quoted with their English label, « Book ».
export default [
  {
    slug: 'setup',
    section: 'use',
    icon: 'wand',
    title: 'Configurer un immeuble',
    summary: 'L’assistant en six étapes, et la suite.',
    blocks: [
      { p: 'L’assistant vous demande en six courtes étapes tout ce dont le planning a besoin. Vos saisies restent sur cet appareil (sans le mot de passe) jusqu’à la dernière étape, qui crée l’immeuble. Vous pouvez tout modifier plus tard.' },
      { callout: 'Hébergé : ouvrez [{app}/setup]({app}/setup). Auto-hébergé : ouvrez l’adresse de votre serveur et touchez « Set one up – it takes 5 minutes ».', tone: 'tip' },
      { h2: 'Les six étapes' },
      {
        steps: [
          { title: 'Immeuble', text: 'Le nom de l’immeuble et les appartements. « Quick fill » crée des noms comme « Rez gauche, Rez droite, 1er gauche ». Touchez un point pour changer la couleur d’un appartement.' },
          { title: 'Buanderie', text: 'Combien de lave-linge, sèche-linge et étendages il y a, et comment on les réserve : **tout ensemble** (une buanderie par réservation), **chaque machine séparément** ou **de façon mixte**, par exemple lave-linge et sèche-linge ensemble, l’étendage à part.' },
          { title: 'Horaires', text: 'Les jours de lessive et comment une journée est découpée en créneaux : journée entière, 2 ou 3 créneaux, toutes les 2 heures ou vos propres horaires, au besoin différents certains jours. Une vue de la semaine montre le résultat.' },
          { title: 'Planning fixe', text: 'Qui a quel créneau régulièrement, comme des rendez-vous qui se répètent : chaque semaine, toutes les 2 à 4 semaines ou une fois par mois (p. ex. le premier ou le dernier mardi du mois). L’assistant propose une répartition équitable ; un calendrier mensuel et le « Time per flat » montrent le résultat.' },
          { title: 'Règles', text: 'Combien de réservations supplémentaires sont permises, combien de temps à l’avance, et ce qui arrive aux créneaux non utilisés. Un résumé en mots simples montre ce qui s’applique.' },
          { title: 'Accès', text: 'Prénom, e-mail et mot de passe de l’administration. Vous choisissez aussi **Gratuit** (à imprimer) ou **Plus** ({trial} jours offerts, sans données de paiement) et voyez un résumé de tout.' },
        ],
      },
      { callout: 'Utilisez des noms comme « 2e gauche » plutôt que des noms de famille. Le planning est affiché dans la buanderie, et avec Plus tout l’immeuble le voit en ligne.', tone: 'privacy' },
      { h2: 'Ensuite : imprimer ou inviter' },
      {
        list: [
          '**Gratuit :** imprimez le planning sous « Manage → Print » : deux semaines par page A4, pour chaque machine ou local, jusqu’à {printFree} semaines à la fois (une année entière avec Plus). La fenêtre d’impression peut aussi l’enregistrer en PDF. Un changement plus tard ? Il suffit de réimprimer.',
          '**Plus :** la page « Invite » explique la suite : imprimer l’affiche avec le code QR et l’afficher dans la buanderie, et donner à chaque appartement son code d’accès à 6 chiffres. Les cartes avec leur propre code QR le remplissent automatiquement.',
          '**Auto-hébergé, et un seul immeuble ?** Mettez ensuite `ALLOW_SIGNUP=false` pour que personne ne crée d’autres immeubles.',
        ],
      },
    ],
  },
  {
    slug: 'residents',
    section: 'use',
    icon: 'users',
    title: 'Pour les habitant·e·s',
    summary: 'Rejoindre, réserver, libérer : le planning au quotidien.',
    blocks: [
      { callout: 'Vous utilisez le planning en ligne quand votre immeuble a [Plus](/pricing). Sinon, il est affiché sur papier dans la buanderie, et l’application indique « The online schedule is paused ».' },
      { h2: 'Rejoindre' },
      {
        steps: [
          { title: 'Scanner le code QR', text: 'Celui de l’affiche dans la buanderie ou de la carte de votre appartement.' },
          { title: 'Choisir l’appartement', text: 'Et saisir le code d’accès à 6 chiffres. Avec la carte de votre appartement, il est déjà rempli.' },
          { title: 'C’est fait', text: 'Vous restez connecté·e sur cet appareil. Avec un e-mail et un mot de passe, vous pouvez aussi vous connecter sur d’autres appareils – si vous le souhaitez.' },
        ],
      },
      { h2: 'Le planning' },
      { p: 'Chaque couleur représente un appartement. Les créneaux de votre appartement ont un bord épais et une icône de personne. Sur grand écran, vous voyez toute la semaine ; sur téléphone, un jour après l’autre. Touchez le titre de la semaine pour aller à n’importe quel jour.' },
      { h2: 'Ce que vous pouvez faire' },
      {
        table: {
          head: ['Action', 'Comment'],
          rows: [
            ['**Réserver** (« Book »)', 'Touchez un créneau libre et confirmez. En dehors de vos horaires fixes, c’est une réservation supplémentaire ; l’administration fixe combien sont permises par semaine.'],
            ['**Libérer** (« Free up »)', 'Vous n’avez pas besoin de votre créneau ? Libérez-le pour que d’autres puissent le réserver. Tant que personne ne le réserve, vous pouvez le reprendre.'],
            ['**Modifier** (« Edit »)', 'Ajouter une note (« lessive à 60° ») ou n’utiliser qu’une partie du temps, pour que les autres voient quand c’est libre.'],
            ['**Déplacer** (« Move »)', 'Glissez votre créneau sur un créneau libre. Ou touchez-le, puis « Move », puis un créneau libre.'],
            ['**Check-in** (« Check in »)', 'Touchez « Check in » quand vous êtes dans la buanderie. Personne ne peut alors reprendre votre créneau.'],
            ['**Terminé – libérer le reste** (« Done – free the rest »)', 'Fini plus tôt ? Dès maintenant, chaque appartement peut réserver le reste, sans que cela compte comme réservation supplémentaire. « Not done yet » l’annule tant que personne n’a réservé.'],
            ['**Reprendre** (« Take over »)', 'Reprendre le créneau non utilisé d’un autre appartement : selon le règlement après un délai d’attente, à tout moment ou jamais. L’autre appartement est averti.'],
          ],
        },
      },
      { h2: 'Votre page (« My laundry »)' },
      { p: 'Sous « My laundry », vous voyez ce qui vient ensuite, les horaires fixes de votre appartement (« Every other Tuesday, 07:00–17:00 ») et vos notifications. C’est là que vous choisissez si les changements de vos créneaux vous sont aussi envoyés par e-mail, que vous vous abonnez au calendrier et que vous réglez la taille du texte.' },
      { callout: 'Qui a l’adresse de l’abonnement au calendrier voit les horaires de votre appartement. Ne la partagez qu’avec votre ménage.', tone: 'privacy' },
      { h2: 'Comme application sur le téléphone' },
      {
        list: [
          '**Android et ordinateur :** sous « My laundry → As an app », touchez « Install as an app ».',
          '**iPhone et iPad :** dans Safari, touchez « Partager », puis « Sur l’écran d’accueil ».',
          'Ensuite, le planning s’ouvre aussi sans internet et montre le dernier état chargé. Vous pourrez de nouveau réserver dès que vous serez en ligne.',
        ],
      },
      { h2: 'Quand Plus est terminé' },
      { p: 'Vous pouvez encore consulter le planning pendant {view} jours, sans pouvoir rien réserver ni modifier. Ensuite, il est de nouveau affiché sur papier dans la buanderie – jusqu’à ce que l’administration rachète Plus.' },
    ],
  },
  {
    slug: 'admin',
    section: 'use',
    icon: 'sliders',
    title: 'Pour l’administration',
    summary: 'Planning fixe, impression, machines, règles, appartements et Plus.',
    blocks: [
      { p: 'Sous « Manage », vous modifiez tout ce que vous avez configuré dans l’assistant. Les changements s’accumulent dans une barre en bas qui dit ce qui change (« 2 time slots changed · 1 new »). Ils ne s’appliquent qu’après « Save ». Ce qui ne peut pas être annulé demande d’abord confirmation et en nomme les conséquences.' },
      { h2: 'Les rubriques' },
      {
        table: {
          head: ['Rubrique', 'Ce que vous y faites'],
          rows: [
            ['**Regular schedule**', 'Qui a quel créneau régulièrement. Le même éditeur que dans l’assistant, avec calendrier mensuel et « Time per flat ». Glissez des créneaux (pour les déplacer ou les échanger), ou « peignez » : choisissez un appartement, puis touchez ou balayez des créneaux.'],
            ['**Machines & times**', 'Machines et locaux, leurs créneaux par jour et le mode de réservation. Une buanderie peut être divisée en machines et regroupée à nouveau ; horaires, planning fixe et réservations sont conservés.'],
            ['**Rules** · Plus', 'Réservations supplémentaires par semaine (comptées en créneaux ou en jours), combien de temps à l’avance on peut réserver et quand d’autres peuvent reprendre un créneau.'],
            ['**Print**', 'Deux semaines par page A4, à partir de la semaine de votre choix, pour les machines et locaux choisis : en version gratuite jusqu’à {printFree} semaines à la fois, avec Plus une année entière. La fenêtre d’impression peut aussi enregistrer en PDF.'],
            ['**Invite** · Plus', 'Imprimer l’affiche avec le code QR et partager ou renouveler le lien d’invitation.'],
            ['**Flats**', 'Noms, couleurs et codes d’accès. Un nouveau code invalide l’ancienne carte ; qui est déjà connecté le reste.'],
            ['**People** · Plus', 'Qui appartient à quel appartement. Retirer des personnes.'],
            ['**Activity** · Plus', 'Qui a réservé, libéré ou modifié quoi, et quand.'],
            ['**Settings**', 'Nom, fuseau horaire et langue de l’immeuble, si l’on peut rejoindre l’immeuble avec le code QR et s’il existe une vue publique du planning.'],
            ['**Plus**', 'Essayer, acheter ou prolonger Plus, et voir les paiements passés.'],
          ],
        },
      },
      { p: 'En version gratuite, les rubriques qui font partie de Plus sont visibles, mais inactives et marquées Plus.' },
      { h2: 'Gérer Plus' },
      {
        list: [
          '**Essayer :** chaque immeuble peut utiliser Plus gratuitement pendant {trial} jours, une fois, sans données de paiement – à la dernière étape de la configuration ou avec l’offre sous « Manage ». Un e-mail arrive {trialRemind} jours avant la fin.',
          '**Acheter :** sous « Manage → Plus », pour un an, sur la page de paiement sécurisée de Stripe. Vous payez par appartement actif. Si vous achetez pendant l’essai, l’année ne commence qu’à la fin de celui-ci.',
          '**Prolonger :** durant les {renew} derniers jours ; la nouvelle année commence à la fin de l’ancienne. Nous vous le rappelons par e-mail {remind} jours avant la fin. Rien ne se renouvelle tout seul.',
          '**Un nouvel appartement en cours d’année :** la page « Flats » le demande et ouvre la page de paiement pour sa part jusqu’à la fin de l’année (au moins CHF {min}). L’appartement démarre une fois payé ; personne d’autre ne remarque rien.',
          '**Quand Plus se termine :** les habitant·e·s peuvent encore consulter le planning pendant {view} jours. Ensuite, l’immeuble repasse en Gratuit : vous continuez à modifier et imprimer le planning, et tout reste enregistré.',
        ],
      },
      { h2: 'Règles pour reprendre un créneau' },
      {
        list: [
          '**Après le délai d’attente** (par défaut) : seulement une fois le créneau commencé et le délai écoulé, et seulement si personne n’a fait de check-in.',
          '**À tout moment**, tant que personne n’a fait de check-in.',
          '**Jamais :** les créneaux des autres ne peuvent pas être repris.',
        ],
      },
      { p: 'L’appartement concerné reçoit une notification dans l’application et, s’il l’a choisi, un e-mail.' },
      { h2: 'Quand des horaires fixes se chevauchent' },
      { p: 'Si deux horaires fixes s’appliquent au même créneau, celui qui se répète le moins souvent l’emporte. C’est ainsi que fonctionne « chaque lundi l’appartement A, mais le premier lundi du mois l’appartement B ».' },
      { h2: 'Vue publique du planning' },
      { p: 'Pour un écran dans la buanderie, il existe une vue sans connexion, sans notes et sans noms de personnes. Elle se met à jour chaque minute. Vous l’activez sous « Settings » ; elle fait partie de Plus.' },
    ],
  },
  {
    slug: 'self-hosting',
    section: 'run',
    icon: 'server',
    title: 'Auto-hébergement',
    summary: 'Faire tourner Waschplaner sur votre propre serveur avec Docker.',
    blocks: [
      { p: 'Waschplaner se compose de trois conteneurs : la base de données (PostgreSQL 17), le serveur (Go) et l’interface web (nginx). Docker Compose les démarre ensemble. En auto-hébergement, vous avez toutes les fonctions, et Plus ne coûte rien si vous ne configurez pas de paiements.' },
      { h2: 'Ce qu’il vous faut' },
      {
        list: [
          'Un serveur Linux, un mini-PC ou un NAS avec **Docker** et **Docker Compose**.',
          'Une **adresse** (domaine ou sous-domaine) pour que les habitant·e·s accèdent au planning en HTTPS.',
          'En option, un **serveur de messagerie** (SMTP) pour les notifications par e-mail et « mot de passe oublié ».',
        ],
      },
      { h2: 'Démarrage rapide' },
      { p: 'Pour essayer sur votre ordinateur :' },
      { code: 'git clone {repo}.git waschplaner\ncd waschplaner\ndocker compose up -d --build' },
      { p: 'Ouvrez ensuite [http://localhost:8080](http://localhost:8080) et touchez « Set one up – it takes 5 minutes ». La base de données est créée et mise à jour automatiquement au démarrage.' },
      { h2: 'En production' },
      {
        steps: [
          { title: 'Créer les réglages', text: 'Copiez le modèle et générez un mot de passe solide pour la base de données :', code: 'cp .env.example .env\nopenssl rand -base64 32' },
          { title: 'Définir les valeurs importantes', text: '`POSTGRES_PASSWORD` avec le mot de passe généré, `PUBLIC_URL` avec votre adresse (p. ex. `https://lessive.example.ch`), `COOKIE_SECURE=true` dès que HTTPS fonctionne, et `FAKE_STRIPE=false` pour Plus sans paiement. Toutes les valeurs sont décrites sous [Configuration](/docs/configuration).' },
          { title: 'Démarrer', code: 'docker compose up -d --build' },
        ],
      },
      { h2: 'Plus et paiements' },
      { p: '`docker-compose.yml` définit `FAKE_STRIPE=true`. Plus est alors « payé » sur une page de paiement simulée, en mode test et sans argent réel, pour tout essayer. En production, choisissez l’une des deux voies :' },
      {
        list: [
          '**Sans paiement**, p. ex. pour votre seul immeuble : `FAKE_STRIPE=false` et `STRIPE_SECRET_KEY` vide. Vous activez alors simplement Plus sous « Manage → Plus », gratuitement.',
          '**Avec paiements via Stripe :** mettez votre clé dans `STRIPE_SECRET_KEY`. Testez d’abord avec une clé de test (`sk_test_…`) et la carte de test 4242 4242 4242 4242 ; les paiements de test ne comptent plus dès qu’une vraie clé est définie. Une clé l’emporte toujours sur `FAKE_STRIPE`.',
        ],
      },
      { code: 'FAKE_STRIPE=false\nSTRIPE_SECRET_KEY=sk_test_…\nSTRIPE_WEBHOOK_SECRET=whsec_…\nSTRIPE_PAYMENT_METHODS=card,twint\nPLUS_PRICE=2\nPLUS_CURRENCY=CHF', title: '.env' },
      { p: 'Recommandé : dans le tableau de bord Stripe, sous « Developers → Webhooks », ajoutez un webhook vers `https://<votre adresse>/api/stripe/webhook` avec les événements `checkout.session.completed` et `checkout.session.async_payment_succeeded`, et mettez son secret de signature dans `STRIPE_WEBHOOK_SECRET`. Les paiements comptent alors même si quelqu’un ferme la page de paiement avant de revenir.' },
      { callout: 'Waschplaner n’envoie pas de quittances. Activez les e-mails pour les paiements réussis dans le tableau de bord Stripe. TWINT exige la monnaie CHF et doit être activé dans le tableau de bord.', tone: 'tip' },
      { h2: 'HTTPS avec Caddy' },
      { p: 'L’interface web écoute sur le port 8080, sans chiffrement. Un reverse proxy placé devant s’occupe du HTTPS. Avec [Caddy](https://caddyserver.com), ce fichier suffit ; Caddy obtient le certificat tout seul :' },
      { code: 'lessive.example.ch {\n\treverse_proxy localhost:8080\n}', title: 'Caddyfile' },
      { callout: 'Mettez `HTTP_PORT=127.0.0.1:8080` pour que seul Caddy atteigne le port 8080. Et n’oubliez pas `COOKIE_SECURE=true` et `PUBLIC_URL=https://…` : l’adresse figure dans les e-mails, les liens de calendrier et d’invitation, et la page de paiement y revient.', tone: 'warn' },
      { h2: 'Votre seul immeuble' },
      { p: 'Une fois votre immeuble créé, mettez `ALLOW_SIGNUP=false` et redémarrez. Personne d’autre ne peut alors créer d’immeuble sur votre serveur.' },
      { h2: 'E-mail' },
      { p: 'Sans serveur de messagerie, il n’y a que des notifications dans l’application, et « mot de passe oublié » ne fonctionne pas. Les e-mails aux habitant·e·s font partie de Plus. Saisissez les données de votre fournisseur de messagerie :' },
      { code: 'SMTP_HOST=smtp.example.ch\nSMTP_PORT=587\nSMTP_USER=lessive@example.ch\nSMTP_PASSWORD=…\nSMTP_FROM=Waschplaner <lessive@example.ch>', title: '.env' },
      { h2: 'Protection contre le spam' },
      { p: 'En option, Google reCAPTCHA protège les formulaires publics : connexion, création d’un immeuble, adhésion à un immeuble et mot de passe oublié. Il est désactivé tant que les deux clés ne sont pas définies.' },
      { callout: 'Avec reCAPTCHA, le navigateur charge un script de Google sur ces pages. Mentionnez-le dans votre déclaration de protection des données.', tone: 'privacy' },
      { h2: 'Sauvegardes' },
      { p: 'Toutes les données se trouvent dans la base de données. Pour les sauvegarder dans un fichier :' },
      { code: 'docker compose exec -T db sh -c \'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"\' | gzip > waschplaner-$(date +%F).sql.gz' },
      { p: 'Et pour les restaurer dans une base de données vide :' },
      { code: 'gunzip -c waschplaner-2026-09-23.sql.gz | docker compose exec -T db sh -c \'psql -U "$POSTGRES_USER" "$POSTGRES_DB"\'' },
      { callout: 'Programmez une tâche cron quotidienne et conservez quelques sauvegardes à un autre endroit.', tone: 'tip' },
      { h2: 'Mettre à jour' },
      { code: 'git pull\ndocker compose up -d --build' },
      { p: 'Les modifications de la base de données s’exécutent automatiquement au démarrage du serveur. Faites d’abord une sauvegarde.' },
      { h2: 'Contribuer' },
      { p: 'Comment lancer Waschplaner sans Docker, exécuter les tests et vous repérer dans le code : tout est dans le [README]({repo}#readme) (en anglais).' },
    ],
  },
  {
    slug: 'configuration',
    section: 'run',
    icon: 'terminal',
    title: 'Configuration',
    summary: 'Tous les réglages pour votre propre serveur.',
    blocks: [
      { p: 'Docker Compose lit le fichier `.env` dans le dossier du projet. Après une modification, `docker compose up -d` applique les nouvelles valeurs. « Par défaut » est la valeur de `docker-compose.yml`.' },
      { h2: 'Bases' },
      {
        table: {
          head: ['Variable', 'Par défaut', 'Signification'],
          rows: [
            ['`POSTGRES_PASSWORD`', '`waschplan`', 'Le mot de passe de la base de données. **À changer impérativement en production.**'],
            ['`POSTGRES_USER`', '`waschplan`', 'Le nom d’utilisateur de la base de données.'],
            ['`POSTGRES_DB`', '`waschplan`', 'Le nom de la base de données.'],
            ['`HTTP_PORT`', '`8080`', 'Le port sur le serveur. `127.0.0.1:8080` le rend accessible seulement en local, p. ex. derrière un reverse proxy.'],
            ['`PUBLIC_URL`', '`http://localhost:8080`', 'L’adresse à laquelle les habitant·e·s ouvrent Waschplaner. Elle figure dans les e-mails, les liens de calendrier et d’invitation, et protège les formulaires (CSRF).'],
            ['`COOKIE_SECURE`', '`false`', '`true` dès que Waschplaner fonctionne en HTTPS.'],
            ['`ALLOW_SIGNUP`', '`true`', '`false` pour que personne ne puisse créer d’autres immeubles.'],
          ],
        },
      },
      { h2: 'Plus et paiements' },
      {
        table: {
          head: ['Variable', 'Par défaut', 'Signification'],
          rows: [
            ['`PLUS_PRICE`', '`2`', 'Le prix par appartement et par an, p. ex. `1` ou `4.50`.'],
            ['`PLUS_CURRENCY`', '`CHF`', 'La monnaie sous forme de code, p. ex. `CHF` ou `EUR`. Seulement des monnaies à deux décimales.'],
            ['`FAKE_STRIPE`', '`true`', 'Une page de paiement simulée en mode test ; rien n’est débité. `false` et aucune clé : Plus est un interrupteur gratuit.'],
            ['`STRIPE_SECRET_KEY`', '–', 'Clé Stripe : `sk_test_…` pour le mode test, `sk_live_…` pour les vrais paiements. L’emporte sur `FAKE_STRIPE`.'],
            ['`STRIPE_WEBHOOK_SECRET`', '–', 'Le secret de signature du webhook. Confirme les paiements même si personne ne revient de la page de paiement.'],
            ['`STRIPE_PAYMENT_METHODS`', '–', 'Moyens de paiement, p. ex. `card,twint`. Vide : ce qui est activé dans le tableau de bord Stripe.'],
          ],
        },
      },
      { h2: 'E-mail' },
      {
        table: {
          head: ['Variable', 'Par défaut', 'Signification'],
          rows: [
            ['`SMTP_HOST`', '–', 'Le serveur de messagerie. Vide : notifications dans l’application seulement.'],
            ['`SMTP_PORT`', '`587`', 'Le port du serveur de messagerie.'],
            ['`SMTP_USER`', '–', 'Nom d’utilisateur auprès du serveur de messagerie.'],
            ['`SMTP_PASSWORD`', '–', 'Mot de passe auprès du serveur de messagerie.'],
            ['`SMTP_FROM`', '`Waschplaner <noreply@example.com>`', 'L’expéditeur des e-mails.'],
          ],
        },
      },
      { h2: 'reCAPTCHA' },
      {
        table: {
          head: ['Variable', 'Par défaut', 'Signification'],
          rows: [
            ['`RECAPTCHA_SITE_KEY`', '–', 'La clé publique de Google. reCAPTCHA n’est actif que si les deux clés sont définies.'],
            ['`RECAPTCHA_SECRET`', '–', 'La clé secrète de Google.'],
            ['`RECAPTCHA_VERSION`', '`v2`', '`v2` : la case « Je ne suis pas un robot ». `v3` : invisible, avec un score.'],
            ['`RECAPTCHA_MIN_SCORE`', '`0.5`', 'Seulement avec `v3` : le score minimal accepté, de 0 à 1.'],
          ],
        },
      },
      { h2: 'Avancé' },
      { p: 'Ces valeurs ne figurent pas dans `.env`. Pour les modifier, changez-les ou ajoutez-les dans `docker-compose.yml` sous `api` → `environment`.' },
      {
        table: {
          head: ['Variable', 'Par défaut', 'Signification'],
          rows: [
            ['`DATABASE_URL`', 'depuis `POSTGRES_*`', 'La connexion à la base de données.'],
            ['`LISTEN_ADDR`', '`:8080`', 'L’adresse sur laquelle le serveur écoute dans le conteneur.'],
            ['`TRUST_PROXY`', '`true`', 'Reprendre l’adresse des visiteurs depuis `X-Forwarded-For`. Important pour limiter les tentatives de connexion.'],
            ['`AUTH_RATE_LIMIT`', '`10`', 'Combien de connexions, inscriptions et adhésions une adresse peut tenter par minute.'],
            ['`MAIL_LOG`', '`false`', '`true` : écrire les e-mails dans le journal au lieu de les envoyer, pour le développement.'],
          ],
        },
      },
    ],
  },
  {
    slug: 'glossary',
    section: 'more',
    icon: 'book',
    title: 'Glossaire',
    summary: 'Les mots de Waschplaner, en allemand et en anglais, avec leur sens en français.',
    blocks: [
      { p: 'L’application est en allemand et en anglais. Voici ses mots dans les deux langues, avec ce qu’ils veulent dire.' },
      {
        table: {
          head: ['Deutsch', 'English', 'Signification'],
          rows: [
            ['Plan', 'Schedule', 'Le planning : la vue de la semaine que tout le monde voit.'],
            ['Fester Plan, feste Zeit', 'Regular schedule, regular time', 'Le planning fixe : qui a quel créneau de façon régulière, comme un rendez-vous qui se répète.'],
            ['Zeitfenster', 'Time slot', 'Le créneau : le temps qu’un appartement réserve en une fois, p. ex. 07:00–12:00.'],
            ['Buchen', 'Book', 'Réserver un créneau libre.'],
            ['Zusätzlich', 'Extra', 'Une réservation supplémentaire, en dehors des horaires fixes ; limitée par semaine.'],
            ['Freigeben', 'Free up', 'Libérer un créneau pour que d’autres puissent le réserver.'],
            ['Übernehmen', 'Take over', 'Reprendre le créneau non utilisé d’un autre appartement ; celui-ci est averti.'],
            ['Fertig – Rest freigeben', 'Done – free the rest', 'Terminé plus tôt : le reste du créneau en cours est libre pour tous.'],
            ['Rest buchen', 'Book the rest', 'Réserver le reste d’un créneau qu’un autre appartement a terminé plus tôt. Jamais une réservation supplémentaire.'],
            ['Einchecken', 'Check in', '« Je suis dans la buanderie. » Protège le créneau.'],
            ['Meine Wäsche', 'My laundry', 'Votre page : prochains créneaux, horaires fixes, notifications.'],
            ['Haus', 'House', 'L’immeuble, avec son planning et ses règles.'],
            ['Wohnung', 'Flat', 'L’appartement, un ménage. Les réservations appartiennent aux appartements.'],
            ['Bewohner:in', 'Resident', 'Habitant·e : personne qui a rejoint l’immeuble avec le code d’accès d’un appartement.'],
            ['Verwaltung', 'Administrator', 'L’administration : la personne qui configure et gère le planning.'],
            ['Waschküche', 'Laundry room', 'La buanderie : plusieurs machines réservées ensemble.'],
            ['Maschine', 'Machine', 'Lave-linge, sèche-linge ou étendage.'],
            ['Zugangscode', 'Access code', 'Le code d’accès : les 6 chiffres sur la carte d’un appartement, pour rejoindre l’immeuble.'],
            ['Aushang', 'Poster', 'L’affiche imprimée avec le code QR de l’immeuble.'],
            ['Gratis', 'Free', 'Gratuit : le planning sans Plus, que l’administration crée et imprime, jusqu’à {printFree} semaines à la fois.'],
            ['Plus', 'Plus', 'Tout le monde utilise le planning en ligne, avec e-mails, abonnement au calendrier et vue publique.'],
            ['Öffentliche Plan-Ansicht', 'Public schedule view', 'La vue publique : le planning sans connexion, pour un écran dans la buanderie.'],
            ['Kaufen, verlängern', 'Buy, renew', 'Acheter une année de Plus ; prolonger ajoute une année.'],
            ['Bezahlseite', 'Payment page', 'La page de Stripe où l’administration paie.'],
          ],
        },
      },
    ],
  },
]
